celery.beat.Scheduler: fix _when to make tz-aware (#3851)
celery/celery pull request #3852
Opened 2017-02-17 22:23 UTC by Taywee

Fixes #3851

2017-03-02 07:18 UTC, thedrow commented
It feels like some test coverage is required in order to ensure this won't regress. Can you add a test that verifies that celery beat works with multiple time zones?

2017-04-16 07:03 UTC, thedrow commented
Ping @Taywee

2017-04-16 16:05 UTC, Taywee commented
I agree that some tests are probably necessary.  I'm not sure how those tests should look, however.  `_when` on its own would be easy enough to test, but unit tests on private methods are usually frowned upon.

2017-04-17 07:08 UTC, thedrow commented
You should test `populate_heap()` and verify that the schedule has been adjusted to the timezone.

2019-05-06 09:11 UTC, auvipy commented
It seems it is fixed, correct me if I am wrong.

2021-11-05 05:28 UTC, auvipy requested changes
please rebase. if you do not have time i will take this over after a week

2025-02-02 08:01 UTC, auvipy reviewed
closing as it seems to be implemented in main branch with other relevant changes. https://github.com/celery/celery/blob/main/celery/beat.py#L299

2025-02-02 08:01 UTC, closed without merging