Added failing test cases for #3885
celery/celery pull request #3982
Opened 2017-04-15 19:35 UTC by thedrow

The tests were contributed by @robpogorzelski

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

Attempt to fix #3885 without hurting eager execution of the canvas.

2017-06-02 16:27 UTC, auvipy reviewed
is it ready for merge?

2017-06-02 16:27 UTC, auvipy commented on t/unit/tasks/test_canvas.py
> +            chord([self.add.si(1, 2)], body=self.mul.s(4), app=self.app),
what si() refers t0? mul means multiply?

2017-06-03 06:40 UTC, thedrow commented on t/unit/tasks/test_canvas.py
> +            chord([self.add.si(1, 2)], body=self.mul.s(4), app=self.app),
mul means multiply yes and what do you mean by t0?

2017-06-03 06:41 UTC, thedrow commented
No, this is just a PR to contain the tests that were contributed by @robpogorzelski.
We need to find the cause of this bug and fix it before we merge this.

2017-06-03 13:01 UTC, auvipy commented on t/unit/tasks/test_canvas.py
> +            chord([self.add.si(1, 2)], body=self.mul.s(4), app=self.app),
i was asking about si(1, 2) :D

2017-06-04 11:28 UTC, thedrow commented on t/unit/tasks/test_canvas.py
> +            chord([self.add.si(1, 2)], body=self.mul.s(4), app=self.app),
`si()` the same as `s` just immutable.

2018-01-19 10:22 UTC, auvipy commented
can we close this? https://github.com/celery/celery/issues/3885

2018-01-19 21:40 UTC, thedrow commented
@auvipy I haven't had the time to actually fix the issue so no.

2021-02-17 13:29 UTC, auvipy commented
https://github.com/celery/celery/issues/3885 might be fixed

2021-11-05 07:32 UTC, auvipy requested changes
was wondering why unit tests are passing!

2026-09-13 06:15 UTC, auvipy commented
closing in favor of https://github.com/celery/celery/pull/10622

2026-09-13 06:15 UTC, closed without merging