Update couchbase API to 3.0.0
celery/celery pull request #6094
Opened 2020-05-14 13:49 UTC by mchataigner

This is a tentative to update couchbase code to 3.0.0 API.
I will need a Couchbase specialist to validate this code.

2020-05-14 14:02 UTC, auvipy commented
python 3.7 n 3.8 is passing the remaining r failing. can you check?

2020-05-14 14:04 UTC, auvipy commented
can you change the Travis Linux from focal to bionic to python 2.7, 3.5, and 3.6?

2020-05-14 14:29 UTC, mchataigner commented
done in a separate PR https://github.com/celery/celery/pull/6096

2020-05-14 14:34 UTC, mchataigner commented
It seems couchbase python client 3.0.0+ has a requirement for python 3.7 on Windows.
According to their readme:
`These are available for at least Python 3.7 on Windows, but we will endeavour to add more`

2020-05-14 14:43 UTC, auvipy commented
lelts keep this for future version of celery

2020-08-18 05:36 UTC, auvipy commented
this should be rebased on master for celery v5

2020-08-25 13:59 UTC, thedrow requested changes

2020-08-25 13:59 UTC, thedrow commented on celery/backends/couchbase.py
> +    # Couchbase = Connection = NotFoundError = None   # noqa
Please do not leave commented out code in the codebase.

2020-08-30 17:35 UTC, thedrow commented
Unfortunately you didn't allow edits from maintainers.
I'm going to replace this PR as I've done the necessary work to merge this.

2020-08-30 17:35 UTC, closed without merging