Expose retry_policy for Redis result backend
celery/celery pull request #6330
Opened 2020-09-02 17:00 UTC by ashb

Rather than adding a new top-level config option, I have used a new key
in the already existing setting `result_backend_transport_options`.

Fixes #6166

2020-09-02 19:29 UTC, ashb commented
Test failed due to an `apt-get` timeout (i.e. random failure)

2020-09-02 21:42 UTC, ashb commented
@auvipy PTAL/restart CI when you have a few spare cycles? Thanks.

2020-09-06 01:46 UTC, auvipy commented on celery/backends/redis.py
> +        retry_policy = super(RedisBackend, self).retry_policy
only super() should be OK on master

2020-09-06 16:35 UTC, ashb commented on celery/backends/redis.py
> +        retry_policy = super(RedisBackend, self).retry_policy
Great! (Force of habit)

2020-09-06 17:10 UTC, thedrow requested changes

2020-09-06 17:10 UTC, thedrow commented on celery/backends/redis.py
> +        retry_policy = super(RedisBackend, self).retry_policy
```suggestion
        retry_policy = super().retry_policy
```

2020-09-08 20:37 UTC, ashb commented on celery/backends/redis.py
> +        retry_policy = super(RedisBackend, self).retry_policy
Done, thanks

2020-09-09 06:25 UTC, auvipy reviewed
are the lint errors related?

2020-09-09 08:38 UTC, thedrow commented
> are the lint errors related?

Yes they are.

2020-09-09 08:38 UTC, thedrow requested changes
Please address the lint failures.

2020-09-09 15:06 UTC, ashb commented
Travis/linted tests passing now.

2020-09-09 17:22 UTC, auvipy approved these changes

2020-09-09 17:22 UTC, merged