Contains a workaround for the capitalized configuration issue
celery/celery pull request #6385
Opened 2020-10-01 17:53 UTC by bastbnl

This is a workaround for issue #6366. It doesn't emit the suggestion

2020-10-04 16:47 UTC, thedrow requested changes
Just a few nitpicks.
Otherwise, LGTM.

2020-10-04 16:47 UTC, thedrow commented on celery/apps/worker.py
> +        if isinstance(config_source, (str, )):
```suggestion
        if isinstance(config_source, str):
```
A tuple is only required if we have multiple types to test `config_source` against.

2020-10-04 16:47 UTC, thedrow commented on celery/apps/worker.py
> +        # Ok this qualifies as a hack for issue #6366. Tried making it less of
```suggestion
        # This qualifies as a hack for issue #6366.
```

2020-10-05 05:08 UTC, auvipy approved these changes

2020-10-05 05:09 UTC, merged

2020-10-05 07:53 UTC, thedrow commented
@auvipy couldn't you see I reviewed the PR and had some suggestions?
Why did you merge this anyway???