Fix max_retries override
celery/celery pull request #6436
Opened 2020-10-24 13:51 UTC by Ixiodor

## Description
This seems a better patch for #6433

2020-10-26 05:58 UTC, auvipy requested changes
1 unit test is failing. could you please recheck?

2020-10-26 14:36 UTC, auvipy requested changes
can you add an integration test for this?

2020-10-26 18:33 UTC, Ixiodor commented
There is another BUG.
Explicit raised Exceptions are raised as "ProtectedException". Trying to fix.

2020-10-28 10:35 UTC, Ixiodor commented
I don't really like how autoretry_for works now. There is an useless layer(autoretry.py). I think it's better to call always retry(task.py) and handle here autoretry_for. 
What happens now is:
Calling self.retry => retry => autoretry_for
Calling raise => autoretry_for => retry

2020-10-28 12:07 UTC, Ixiodor commented
Someone wrote some tests with value returned instead of value expected...I'm fixing all wrong tests pulled out by solving that bug

2020-10-28 13:01 UTC, Ixiodor commented
Less intrusive change.

2020-10-28 15:46 UTC, auvipy commented
@safwanrahman can you try this patch?

2020-10-29 13:46 UTC, auvipy commented
@mchataigner

2020-11-02 10:53 UTC, thedrow commented
Please address the lint errors.

2020-11-02 11:19 UTC, auvipy approved these changes
not sure lint error is related

2020-11-02 11:28 UTC, merged

2020-11-02 16:27 UTC, thedrow commented
It was. I fixed it myself.

2020-11-02 23:31 UTC, Ixiodor commented
@thedrow wich error happened in lint?