Make `setup_default_app` actually set the default app
celery/celery pull request #6526
Opened 2020-12-07 19:05 UTC by akx

Fixes #6525
Refs #6007

## Description

This PR:

* refactors the `set_trap()` context manager into a more reusable internal `_set_app()` context manager
* has `setup_default_app()` actually use that context manager when not using a trap app

This seems like the correct thing to do (after all, otherwise `setup_default_app()` doesn't really use `app`), but I'm afraid people who have assumed `celery_app` _doesn't_ set the app as the default app could be upset by the change.

2020-12-08 11:21 UTC, auvipy requested changes
hey, thanks for tackling this! I would like to see unit & integration tests for these changes. Also, it would be great if we could keep the BC & mention it in the changelog/docs as well

2020-12-16 12:54 UTC, thedrow commented
I think this change is good but it definitely needs test coverage.
@akx Do you have time to do that?

2020-12-23 15:06 UTC, thedrow commented
@akk ping?

2021-01-05 11:09 UTC, akx commented
@thedrow Sorry, I don't think I have the bandwidth for that. With this and other issues with Celery I'm looking into switching to Huey or a bespoke solution instead.

2021-01-06 14:18 UTC, thedrow commented
That's a shame.
I'm sorry you're having such a hard time.

2022-01-01 03:23 UTC, auvipy commented
unit tests seems passing, but codecov report not generated, have to double check before merge.

2022-01-19 16:19 UTC, thedrow commented
I'm closing this since it is going to be resolved in 5.3 with #7149.

2022-01-19 16:19 UTC, closed without merging