Behavior that used to be called only in Python 2.7 environments witho…
celery/celery pull request #6561
Opened 2020-12-24 09:29 UTC by awais786

…ut the simplejson package installed is now always used, and it replaces the original dict subclass with a plain dict after sanity checking the keys. I think this is a mistake, those code blocks should have been removed when dropping Python 2.7 support rather than making them the default behavior.

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

2020-12-24 12:30 UTC, thedrow commented
Can you explain why the previous code is the wrong?

2020-12-24 12:50 UTC, awais786 commented
In my application with v4.4.7 on python3.8 callback object is of type 

its type `type(callback)` is `<class 'celery.canvas.Signature'>` 

`callback` is `test_signals.sample_task(1, '2', user_task_name='Chain: 1, 2, 3')`

`callback.__dict__` representation is 
`{'_app': <Celery user_tasks at 0x1110a0130>, '_type': <@task: test_signals.sample_task of user_tasks at 0x1110a0130>, 'app': <Celery user_tasks at 0x1110a0130>, 'type': <@task: test_signals.sample_task of user_tasks at 0x1110a0130>, 'AsyncResult': <bound method Task.AsyncResult of <@task: test_signals.sample_task of user_tasks at 0x1110a0130>>}
`

--------------------------------------------------------------------------------------------
but on v5.0+ things changed and breaks because it is trying to access `callback.options` and its not available now.

`type(callback)` is `<class 'dict'>`

`callback` is plain dict now 
`{'task': 'test_signals.sample_task', 'args': (1, '2'), 'kwargs': {'user_task_name': 'Chain: 1, 2, 3'}, 'options': {'task_id': '345bd875-8295-4fb7-a243-47d8c7766ded', 'reply_to': '9277f81a-2148-3b05-848d-757be32ee4b5', 'link': [test_signals.sample_task(1, '3')]}, 'subtask_type': None, 'chord_size': None, 'immutable': True}`


and `callback['options']['link'][0].__class__` is now `<class 'celery.canvas.Signature'>`

2020-12-24 16:00 UTC, auvipy requested changes
can you also check this removal not going to regress any existing behavior?

2020-12-24 18:57 UTC, awais786 commented
My old code is working fine and all tests are green in my project.

2020-12-29 18:51 UTC, awais786 commented
@auvipy any plans for this PR ?

2021-04-04 15:10 UTC, thedrow approved these changes

2021-04-04 15:11 UTC, merged