Fix: serialization error when gossip working
celery/celery pull request #6566
Opened 2020-12-28 09:32 UTC by kitsuyui

fix of https://github.com/celery/celery/issues/5075
Pass accept when Gossip getting consumers.

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

2020-12-28 13:51 UTC, auvipy requested changes

2020-12-28 13:51 UTC, auvipy commented on celery/worker/consumer/gossip.py
> +            accept=ev.accept,
hey, thanks for the PR, but this change needs some unit test to get accepted

2021-01-04 20:31 UTC, auvipy commented
> ## Description
> 
> fix of #5075
> Pass accept when Gossip getting consumers.

can you at least add a unit test for this fix?

2021-01-05 02:01 UTC, kitsuyui commented
@auvipy 
Thanks. I'd tried to do that but it will take more time for me.
Or can you write instead of me?

2021-01-06 05:50 UTC, auvipy commented
> @auvipy
> Thanks. I'd tried to do that but it will take more time for me.
> Or can you write instead of me?

you can take your time, I have other priorities todo in celery at the moment

2021-02-24 14:36 UTC, thedrow commented
@kitsuyui Is there a chance that you'll complete this PR soon?

2021-02-24 15:43 UTC, kitsuyui commented
@thedrow No.
I don't have any clue to solve soon. I've tried but the unit test has become too complicated.

2023-10-03 15:12 UTC, jbvsmo commented
Any news on this? As the author said he can't finish is it possible some celery mantainer pick it up, please? cc @auvipy 

This is affecting us greatly with no other fix or workaround

2023-10-03 15:19 UTC, auvipy commented
We need to verify this is working and not creating any regression. Thanks for the ping

2023-10-13 23:31 UTC, rfqu commented
I encountered this issue too and solved by adding 
`accept_content = ['application/json', 'application/x-python-serialize','application/x-pickle2']`

2023-10-14 05:24 UTC, auvipy commented
> I encountered this issue too and solved by adding `accept_content = ['application/json', 'application/x-python-serialize','application/x-pickle2']`

hey! great to know that. is it possible for you to send a PR to improve the docs regarding the issue/solution you mentioned?

2023-10-21 12:00 UTC, wlach commented
> I encountered this issue too and solved by adding `accept_content = ['application/json', 'application/x-python-serialize','application/x-pickle2']`

Based on what I've seen, I don't see how this could fix the problem since the problem is that gossip doesn't respect these settings. I'm pretty sure this PR is the correct solution based on a frustrating encounter with this issue today. 

Is there any chance we could merge this as-is and file a follow-up for a unit test? This is a pretty bad bug: it will affect anyone still using pickle serialization with gossip.

2023-10-22 10:41 UTC, auvipy commented
problem is the patch is making the CI red. which means it will create regression

2023-10-22 14:19 UTC, kitsuyui commented
Hi, sorry for being vague. Sorry for the long delay.

I have quitted the company that required this patch. However, I now have time to develop it. If there is anything I can do to help, I would like to do so.

I have already found a way to reproduce the problem at https://github.com/celery/celery/issues/5075#issuecomment-751647340, so I could try again.

The problem was that I was not able to write the necessary tests well, and I was unable to eliminate concerns about regression. I may still need someone's help in this.

2023-10-23 05:12 UTC, auvipy commented
thanks for coming back! as you shared in your repo https://github.com/kitsuyui/celery/pull/5#issuecomment-1774116373 some changes on these tests would be needed. I currently have a big backlog in celery to clear. so in the mean time if you can try to figure out some sort of test, it would be great

2023-10-26 08:58 UTC, kitsuyui commented
@auvipy Hi. I have updated the commits and description of the pull request.
I have added tests. I have also confirmed that the tests fail if I do not make this change.
I have confirmed that the tests pass on my local environment and on the CI of my fork.
But I am not confident that these tests meet your standards.
Could you please review this?

2023-10-27 06:23 UTC, auvipy commented
thanks for the tests! the failures seems to be github network related. so going to re start the CI

2023-10-31 12:44 UTC, kitsuyui commented
@auvipy Hi, I can't rerun CI because I don't have permissions on the project. Please retry. ☕

2023-11-06 08:57 UTC, Nusnus commented
@kitsuyui 
> @auvipy Hi, I can't rerun CI because I don't have permissions on the project. Please retry. ☕ 

Please rebase on `main`.
CI fixes were pushed.

I will make sure the CI will run if it won't automatically.

2023-11-06 13:14 UTC, auvipy requested changes
please pull from main branch again

2023-11-08 08:40 UTC, kitsuyui commented
@Nusnus @auvipy Hi, I rebased the branch and pushed it again.

2023-11-08 09:31 UTC, Nusnus commented
> @Nusnus @auvipy Hi, I rebased the branch and pushed it again.

Thank you!
I'll review it later today

2023-11-08 10:35 UTC, auvipy approved these changes
looks good to me

2023-11-08 10:37 UTC, merged

2023-11-08 13:40 UTC, kitsuyui commented
@auvipy @Nusnus  Thank you!