exit celery with non zero exit value if failing
celery/celery pull request #6602
Opened 2021-01-18 08:55 UTC by tned73

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

There is an issue with version 5.x for the celery command. If the command is failing, the exit value is still 0. This PR will fix this and exits with the intended exit value.

NOTE: All patches should be made against master, not a maintenance branch like
3.1, 2.5, etc.  That is unless the bug is already fixed in master, but not in
that version series.

If it fixes a bug or resolves a feature request,
be sure to link to that issue via (Fixes https://github.com/celery/celery/issues/6601) for example.
-->

2021-01-18 09:17 UTC, thedrow requested changes
We don't need a specialized exception.
We can simply use [`ctx.fail()`](https://click.palletsprojects.com/en/7.x/api/#click.Context.fail).

2021-01-18 09:28 UTC, tned73 commented
If I look at `ctx.fail()` it has a message parameter and not a exit value parameter. Using this will solve a part of the issue. It will probably exit with value 1 and not the 69 if the `celery inspect ping` fails as version 4.x does.
for my purposes it is not an issue.

please advice on direction to solve this issue

2021-01-18 09:33 UTC, thedrow commented
Huh.
That API is very surprising.

I think we're good to go on this one.

2021-01-18 09:35 UTC, thedrow approved these changes
LGTM

2021-01-18 10:04 UTC, thedrow approved these changes
LGTM

2021-01-19 15:19 UTC, auvipy approved these changes
Looks good. should we merge this as is or need unit test?

2021-01-19 17:32 UTC, thedrow commented
There are no unit tests for the CLI at the time being, unfortunately.
I don't have time to write them, currently.

2021-01-19 17:32 UTC, merged