Add `azureblockblob_base_path` config
celery/celery pull request #6669
Opened 2021-03-09 16:58 UTC by ruaridhw

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

- Allow for a basepath such as 'FolderName/' within the Azure container
- Port across the same pattern from `S3Backend`

2021-03-09 17:54 UTC, ruaridhw commented on docs/userguide/configuration.rst
> +~~~~~~~~~~~~~~~~
Thanks, I've added as v5.1. Let me know if this is incorrect

2021-03-09 17:55 UTC, ruaridhw commented on celery/backends/azureblockblob.py
> +        self.base_path = conf.get('azureblockblob_base_path', '')
Added unit tests however I do this by setting `.base_path`, not by using `conf`. Happy to use the former but I'd just need to redesign the tests in `t/unit/backends/test_azureblockblob.py`

2021-03-10 09:47 UTC, ruaridhw commented on celery/backends/azureblockblob.py
> +        self.base_path = conf.get('azureblockblob_base_path', '')
I've added more tests to cover using `conf`

2021-03-10 09:48 UTC, ruaridhw commented
@auvipy back to you. I can't see how the codecov job can be fixed to be honest... Clearly L46 is covered by tests now.

2021-03-10 11:13 UTC, thedrow requested changes

2021-03-12 14:47 UTC, ruaridhw commented
@thedrow @auvipy, I believe this is ready for merging or another look. As mentioned above, I have added tests covering the whole class so I can't see what would allow the codecov job to pass.

2021-03-13 04:29 UTC, auvipy approved these changes

2021-03-13 04:30 UTC, merged