added https verification check functionality in arangodb backend
celery/celery pull request #6800
Opened 2021-06-03 12:49 UTC by dilipvamsi

The backend throws an error if its an unverified https backend.
Verification will be bypassed as default.

2021-06-03 17:11 UTC, auvipy requested changes
please improve test coverage

2021-06-07 08:23 UTC, dilipvamsi commented
@auvipy Can you please help me out with error.
I'm not sure about it.

```python

t/unit/worker/test_worker.py:417: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Timer(Timer-106, stopped daemon 140250924771072)>

    def stop(self):
        self._is_shutdown.set()
        if self.running:
>           self._is_stopped.wait()
E           AttributeError: 'bool' object has no attribute 'wait'

celery/utils/timer2.py:96: AttributeError
```

2021-06-07 15:28 UTC, thedrow commented
> 
> 
> @auvipy Can you please help me out with error.
> I'm not sure about it.
> 
> ```python
> t/unit/worker/test_worker.py:417: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> self = <Timer(Timer-106, stopped daemon 140250924771072)>
> 
>     def stop(self):
>         self._is_shutdown.set()
>         if self.running:
> >           self._is_stopped.wait()
> E           AttributeError: 'bool' object has no attribute 'wait'
> 
> celery/utils/timer2.py:96: AttributeError
> ```

See #6489.

2021-08-29 07:09 UTC, thedrow approved these changes

2021-08-30 08:03 UTC, auvipy approved these changes

2021-08-30 08:04 UTC, merged