grp is no longer imported unconditionally
celery/celery pull request #6804
Opened 2021-06-06 16:18 UTC by thedrow

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

This fixes a regression introduced in #6600 which caused an import error on non-Unix platforms.

Fixes #6797.

2021-06-06 16:18 UTC, thedrow commented
@voegtlel Could you please verify this patch works for you?

2021-06-06 16:23 UTC, thedrow commented
The test doesn't seem to cover our new code branch.
Any suggestions on how to make the modules disappear?

2021-06-07 00:15 UTC, maybe-sybr requested changes

2021-06-07 00:15 UTC, maybe-sybr commented on t/unit/utils/test_platforms.py
> +               return_value=None):
Probably `patch("celery.platforms.grp", new=None)` and just rely on magic knowledge of the `grp` name - I can't think of a practical alternative that wouldn't cause more potential confusion due to reloading the module and the heavy use of from imports in the celery codebase.

2021-06-07 00:17 UTC, maybe-sybr commented
The change itself lgtm

2021-06-08 13:47 UTC, auvipy approved these changes

2021-06-09 01:43 UTC, maybe-sybr approved these changes
lgtm

2021-06-09 03:40 UTC, merged

2021-06-09 03:41 UTC, auvipy commented
should be on 5.1.1 as it fixes a regression O:)