Fix UnboundLocalError when running celery worker in foreground
celery/celery pull request #6833
Opened 2021-06-30 15:26 UTC by michael-k

## Description

Adds the indentation missed in commit 56a6246c74cd4ed51d12194cf3627b0bdf066bc5. The bug is not present in branch `master`.

Fixes celery/celery#6830

2021-07-01 23:08 UTC, maybe-sybr approved these changes
Whoops, looks like a conflict resolution mistake when backporting 6e5580 onto the 5.0 release branch (as 56a6246). Those two commits should be pretty much identical but the merge from master into #6599 probably confused things.

lgtm! Thanks for the PR @michael-k

2021-07-01 23:11 UTC, maybe-sybr commented
Interesting that I can't seem to start the unit test checks on this PR... I assumed it was because @michael-k might be a first time contributor but that's not the case :/

2021-07-02 05:30 UTC, auvipy commented
> Interesting that I can't seem to start the unit test checks on this PR... I assumed it was because @michael-k might be a first time contributor but that's not the case :/ Perhaps we need to amend to workflow rules to match our stable/release branch names as well?

yup

2021-07-02 05:30 UTC, auvipy approved these changes

2021-07-21 10:30 UTC, thedrow commented
I have updated the workflow.
@michael-k Would you mind rebasing, please?

2021-07-21 10:31 UTC, thedrow approved these changes

2021-07-21 10:46 UTC, michael-k commented
> Would you mind rebasing, please?

There are no new commits in branch `5.0` :shrug:

2021-07-21 11:05 UTC, auvipy requested changes
needs another rebase

2021-07-21 11:28 UTC, michael-k commented
> needs another rebase

Rebase onto what?  Before I can rebase, you need to push something to branch `5.0`.  The changes that pre-commit requests are unrelated to this PR and should be done in `5.0` first.

2021-07-21 12:41 UTC, thedrow commented
> 
> 
> > Would you mind rebasing, please?
> 
> There are no new commits in branch `5.0` 🤷
> 
> Edit: I've recreated the commit to trigger a new workflow run.

Yes I should have cherry-picked it myself.🤦  Sorry.

2021-07-21 13:42 UTC, thedrow commented
CI will run now in this branch.

2021-07-21 13:50 UTC, thedrow commented
The CI still isn't running so this needs more work. I'll keep you posted.

2021-07-21 23:43 UTC, maybe-sybr commented
Looks like the CI failures are unrelated to this diff. Also the pre-commit job put a huge, nasty style commit on the end of this PR which should be sorted out on 5.0 (or master and cherry picked back) rather than here.

## py10 failure
```
  _________________ ERROR collecting t/unit/backends/test_s3.py __________________
  t/unit/backends/test_s3.py:6: in <module>
      from moto import mock_s3
  .tox/3.10-unit/lib/python3.10/site-packages/moto/__init__.py:12: in <module>
      from .cloudformation import mock_cloudformation, mock_cloudformation_deprecated  # flake8: noqa
  .tox/3.10-unit/lib/python3.10/site-packages/moto/cloudformation/__init__.py:2: in <module>
      from .models import cloudformation_backends
  .tox/3.10-unit/lib/python3.10/site-packages/moto/cloudformation/models.py:11: in <module>
      from .parsing import ResourceMap, OutputMap
  .tox/3.10-unit/lib/python3.10/site-packages/moto/cloudformation/parsing.py:366: in <module>
      class ResourceMap(collections.Mapping):
  E   AttributeError: module 'collections' has no attribute 'Mapping'
```

Hmm, I think this should be `collections.abc.Mapping`. Is this broken on master also?

## pypy3 failure
```
```
Seems like we need 6c8c93cfe7e6ab1b06aa070c81394ff0b1a4881f, which was part of the #6635 diff to get CI working of pypy3. The squashed merge commit is 117cd9ca4 and should probably be cherry picked onto the 5.0 branch and then have this rebased on top.

## lint failure
```
  An unexpected error has occurred: CalledProcessError: command: ('/home/runner/work/celery/celery/.tox/lint/bin/python', '-mvirtualenv', '/home/runner/.cache/pre-commit/repo_sawvi81/py_env-python3.7', '-p', 'python3.7')
  return code: 1
  expected return code: 0
  stdout:
      RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.7'
```

## lint failure

It's trying to run under python3.7 which isn't available in the job environment. Surprising, I thought the lint job was supposed to run using tox in a python3.9 environment.

2021-07-22 09:23 UTC, thedrow commented
@maybe-sybr Thanks for helping me with the investigation. ❤️

2021-08-17 12:35 UTC, merged