fix: Pass a `Context` when chaining fail results
celery/celery pull request #6899
Opened 2021-08-05 23:44 UTC by maybe-sybr

## Description

This change ensures that during chaining of failure results, we always
reconstruct a `Context` objects for the request rather than sometimes
passing a dictionary to the backend. This avoids upsetting expectations
in the backend implementations which often expect to be able to use
dotted attribute access on the `request` they are passed

Fixes #6882

2021-08-05 23:51 UTC, maybe-sybr commented
@ppiatko @sp-ivan-alcoceba - could you please try this branch if possible? It should fix the issue, but I'll need to spend a bit of time sanity checking the integration tests to make sure the original bug is captured as a regression test if there isn't one already.

@thedrow @auvipy - What the current status of the integration test in CI? It looks like their not running yet based on the checks which got started on this PR but I haven't had much time recently so I'm a bit behind on where things are at. Just wanting to work out how much I'll need to run through on my end to be confident in getting this merged.

2021-08-06 08:18 UTC, sp-ivan-alcoceba commented
hi @maybe-sybr, 

thank you for the quick response, the fix works for me!

2021-08-06 16:43 UTC, ppiatko commented
@maybe-sybr - The fix also works for me. Thanks so much!

2021-08-06 18:02 UTC, auvipy commented
I am in Eid vacation, I will back to that next week hopefully

2021-08-08 14:45 UTC, thedrow requested changes
Overall this LGTM.
I think that if the context manufacturing code would have been a helper function, I'd be able to detect that it exists more easily.
Other than that, it's solid.

We do need tests for this, however.

2021-08-08 14:45 UTC, thedrow commented on celery/backends/base.py
> +                chain_elem_ctx.group = chain_elem_ctx.options.get('group_id')
This screams "I want to be a helper function" 😄

2021-08-08 14:46 UTC, thedrow commented
> @thedrow @auvipy - What the current status of the integration test in CI? It looks like their not running yet based on the checks which got started on this PR but I haven't had much time recently so I'm a bit behind on where things are at. Just wanting to work out how much I'll need to run through on my end to be confident in getting this merged.

I just rebased it. I'm going to push it forward next week, hopefully.

2021-09-02 01:12 UTC, maybe-sybr commented
I've rebased this on top of current master, but I haven't had time to run through the integration tests to prep this for merge. Given that I noticed the 5.2.0 betas are tagged, I'll leave this for a future release since it's unlikely I'll get to it before 5.2.0 final.

2021-09-02 14:01 UTC, thedrow approved these changes

2021-09-02 14:02 UTC, merged