canvas: fix kwargs argument to prevent recursion (#6810)
celery/celery pull request #6959
Opened 2021-09-16 15:38 UTC by rainbowtux

## Description

When using a beat schedule running a task taking a chord as argument, celery crashed with max recursion depth reached. After debugging, kwargs were discovered to be nested every time \_\_init\_\_ is called. This PR fixes that.

2021-09-16 16:09 UTC, auvipy requested changes
could you please add test coverage for the change?

2021-09-16 22:48 UTC, rainbowtux commented
> could you please add test coverage for the change?

@auvipy what exactly do you expect from me? Only 2 lines were changed and no new paths of execution were created. None of the existing tests breaks. I could try writing a specific test for this with my still limited knowledge of celery internals, but could you please have a look and see if my reasoning regarding the kwargs is correct? Otherwise I might be writing a test for something wrong.

As I see it now, before my changes, the kwargs argument is added in a dict with 'kwargs': kwargs and that dict is assigned to the kwargs parameter of Signature.\_\_init\_\_, which results in the nesting and recursion and I took that away. It also explains why the problem does not always shows: only repeatedly serializing/deserializing the chord causes the \_\_init\_\_ function to be called over and over with deeper going kwargs every time. I just would like to know your opinion with regard to potential issues somewhere else. Both existing unit tests nor my personal real-life testing did uncover any issues.

Thank you for your time!

2021-09-17 00:06 UTC, rainbowtux commented
> could you please add test coverage for the change?

I came up with a test... it seems to prove the point: running on the master branch the test fails, on this branch it works. It verifies whether or not the kwargs get nested.

2021-09-17 09:37 UTC, auvipy approved these changes

2021-09-17 09:41 UTC, merged