fix register_task method
celery/celery pull request #7043
Opened 2021-11-05 12:36 UTC by helloninglei

fix cannot pass parameters to add_autoretry_behaviour when call register_task method

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

2021-11-05 17:53 UTC, auvipy requested changes
can you add unit and integration test for this? along with docs change?

2021-11-05 17:53 UTC, auvipy commented
any related issue?

2021-11-06 03:23 UTC, helloninglei commented
> any related issue?

related issue:  https://github.com/celery/celery/issues/4684

2021-11-06 07:21 UTC, auvipy requested changes
ok i will accept this can you add few lines of unit test which shows this is working properly?

2021-11-06 17:25 UTC, auvipy approved these changes

2021-11-06 17:25 UTC, merged