fix: task expiration is timezone aware if needed
celery/celery pull request #7065
Opened 2021-11-09 16:39 UTC by gabor-boros

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

In #6957 the changes introduced checking for datetime objects for task expiration, though the implementation is not considering that the expiration date can be set with or without timezone. Therefore the expiration second calculation for the task can raise a `TypeError`.

This fix is related to a conversation on #6736.

2021-11-09 17:27 UTC, gabor-boros commented
@thedrow @auvipy I have a wild guess that LGTM found the issues because the files were modified, though I was not even close to those lines where the issues were reported.

2021-11-10 05:26 UTC, auvipy reviewed
i have triggered the CI. ignore the lgtm warning for now

2021-11-10 05:35 UTC, auvipy requested changes
can you please recheck the CI failures please?

2021-11-10 05:36 UTC, auvipy commented
=========================== short test summary info ============================
  FAILED t/unit/tasks/test_tasks.py::test_tasks::test_regular_task - AssertionE...
  = 1 failed, 2624 passed, 14 skipped, 3 xfailed, 35 warnings in 103.02s (0:01:43) =
  ERROR: InvocationError for command /home/runner/work/celery/celery/.tox/3.8-unit/bin/pytest --maxfail=10 -v --cov=celery --cov-report=xml --cov-report term (exited with code 1)

2021-11-10 05:38 UTC, auvipy commented
@nicolaerosia

2021-11-11 15:19 UTC, gabor-boros commented
@auvipy the tests are fixed

2021-11-11 17:19 UTC, auvipy commented
can you please pull https://github.com/celery/celery/pull/7077 from master branch?

2021-11-12 06:49 UTC, gabor-boros commented
@auvipy Rebased and pushed.

2021-11-12 08:31 UTC, auvipy approved these changes

2021-11-12 08:38 UTC, merged

2021-11-15 06:35 UTC, gabor-boros commented
@auvipy @thedrow Do you have any insights when this fix will be released on PyPI?

2022-08-17 15:46 UTC, auvipy commented
can you comment on this please? https://github.com/celery/celery/issues/6736#issuecomment-1218169793