Explicitly define SQS dependencies
celery/celery pull request #7071
Opened 2021-11-10 11:32 UTC by hannseman

Fixes: https://github.com/celery/celery/issues/7070

2021-11-10 12:07 UTC, auvipy requested changes
you can  check this as well https://github.com/celery/celery/pull/7069/files

2021-11-10 12:21 UTC, hannseman commented
@auvipy not really sure what you mean but looks like you pulled the changes from this PR to yours so I guess this one can be closed 🤷

2021-11-10 12:24 UTC, auvipy commented
to check if windows build actually passes with this change, which is still failing, can you check that branch?

2021-11-10 12:33 UTC, hannseman commented
> to check if windows build actually passes with this change, which is still failing, can you check that branch?

Ah I see.

2021-11-10 12:55 UTC, hannseman commented on requirements/extras/sqs.txt
> +urllib3>=1.26.7 # Unittests are failing with urllib3>=1.28
Not sure about this urllib3 dependency. I grabbed it from https://github.com/celery/kombu/commit/f3b04558fa0df4ecc383c93e0b3b300d95e17c47

The comment about version 1.28 and above breaking no longer makes much sense but from what I can see no 1.28 version exists for urllib3, see https://pypi.org/project/urllib3/#history 🤔

2021-11-10 13:09 UTC, hannseman commented on requirements/extras/sqs.txt
> +pycurl~=7.44.1
Note that this version do not have any wheels. Latest version with wheels is [7.43.0.5](https://pypi.org/project/pycurl/7.43.0.5/#files)

2021-11-11 05:57 UTC, auvipy commented
> you can check this as well https://github.com/celery/celery/pull/7069/files

closing in favor of it, as it cover more broader change. thanks for you time reporting and investigation.

2021-11-11 05:57 UTC, closed without merging