Reduce prefetch count on restart and gradually restore it
celery/celery pull request #7350
Opened 2022-03-13 12:55 UTC by thedrow

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryproject.org/en/master/contributing.html).

## Description

2022-04-03 11:48 UTC, dobosevych commented
@auvipy there was an issue with Mock * int that I fixed in this PR

2022-05-30 14:44 UTC, thedrow commented
You're right. It needs to be documented.

2022-06-03 06:32 UTC, matusvalo approved these changes
LGTM

2022-06-06 04:37 UTC, auvipy requested changes
we actually need this documented.

2022-06-09 08:45 UTC, thedrow commented
Yes. I'm adding more logs now and this feature will be mentioned in the user guide

2022-06-16 09:15 UTC, auvipy commented on docs/userguide/workers.rst
> +====================================================
i think just version added 5.3 notation needed only here

2022-06-22 10:03 UTC, merged

2022-06-22 10:04 UTC, auvipy commented
thanks!