Annotate `celery/fixups`
celery/celery pull request #7399
Opened 2022-04-03 05:40 UTC by Kludex

2022-04-03 06:03 UTC, Kludex commented on celery/fixups/django.py
> +    return None
> Be consistent in return statements. Either all return statements in a function should return an expression, or none of them should. If any return statement returns an expression, any return statements where no value is returned should explicitly state this as return

https://peps.python.org/pep-0008/#programming-recommendations

It's either this or `# type: ignore[return]`. I'm not attached to any option.

2022-04-12 13:12 UTC, auvipy requested changes

2022-04-12 13:55 UTC, merged

2022-04-12 13:55 UTC, auvipy commented
OK let's go with some of them

2022-04-12 13:58 UTC, Kludex commented
Thanks 👍 

I'll try to spend more time on each `Any` to see if I can do better on the next ones. 👍