Make start_worker, setup_default_app reusable outside of pytest
celery/celery pull request #7503
Opened 2022-05-01 05:15 UTC by yonran

`start_worker` and `setup_default_app` are generator functions wrapped in `@contextmanager`. Generally, @contextmanager requires the `yield` statement to be wrapped in a `try`-`finally` statement to guarantee cleanup. This is not an issue if these functions are only called from @pytest.fixture, which never passes exceptions to the generator. But to use these context managers outside of @pytest.fixture, they need to use the more general try-finally pattern so that they do not hang.

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/master/contributing.html).

## Description

I don’t use pytest at my firm, but I would like to use the `start_worker` helper function because the [testing guide](https://docs.celeryq.dev/en/stable/userguide/testing.html) says that “The eager mode enabled by the [`task_always_eager`](https://docs.celeryq.dev/en/stable/userguide/configuration.html#std-setting-task_always_eager) setting is by definition not suitable for unit tests.” However, when I tried using `start_worker` in a `with` statement, when the code raised an exception it would cause python to hang forever.

Make start_worker and setup_default_app [@contextmanager](https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager) pattern of wrapping the `yield` statement in a `try`-`finally` compound statement.

2022-05-01 06:24 UTC, auvipy requested changes
also can you have a look at unit tests

2022-05-01 06:24 UTC, auvipy commented on t/unit/contrib/test_worker.py
> +    # https://github.com/celery/celery/blob/v4.4.7/celery/app/log.py#L95
why not ref code from master branch?

2022-05-01 09:13 UTC, auvipy commented
just rebase the ci changes please

2022-05-01 19:22 UTC, yonran commented on t/unit/contrib/test_worker.py
> +    # https://github.com/celery/celery/blob/v4.4.7/celery/app/log.py#L95
I removed the absolute references

2022-05-01 19:25 UTC, yonran commented
> just rebase the ci changes please

I have rebased to squash the `isort` pre-commit commit.

2022-05-02 10:41 UTC, auvipy approved these changes

2022-05-02 10:43 UTC, auvipy commented
related https://github.com/akx/celery/commit/1415e9b0d1a9186971179fff286d478fc7b64d30

2022-05-02 10:48 UTC, merged