beat: Suppress banner output with the quiet option
celery/celery pull request #7608
Opened 2022-07-05 02:45 UTC by gabrielsoldani

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/master/contributing.html).

## Description

This adds missing support for the quiet command line option
(`--quiet` or `-q`) for the celery beat command, which suppresses
banner and version information output.

Fixes #5836.

2022-07-05 04:42 UTC, auvipy requested changes
you need to add unit test using pytest-click, there is some test already, which you can check for ref. also documentation might be needed

2022-07-05 04:43 UTC, auvipy commented
https://github.com/celery/celery/blob/master/t/unit/bin/test_worker.py

2022-07-05 12:49 UTC, thedrow approved these changes

2022-07-06 16:21 UTC, auvipy approved these changes
thanks for the tests

2022-07-06 16:22 UTC, merged