Use spawn pool on all platforms, not just Windows
celery/celery pull request #7612
Opened 2022-07-06 20:31 UTC by itamarst

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/master/contributing.html).

## Description

Fixes #6036 

Rather than making the pool strategy configurable, this always uses `spawn`, for the following reason:

* `fork()` without `execve()` is fundamentally broken. See the many many complaints in #6036, and also https://pythonspeed.com/articles/python-multiprocessing/. I have helped multiple people fix mysterious problems caused by `fork()` without `execve()` as well; it's just not possible to work correctly.
* `fork()` without `execve()` has no benefits! It won't save much memory: shared libraries and the Python executable will already be shared by the OS, and Python objects trigger copy-on-write anytime e.g. a refcount changes. It will speed up startup, very slightly. Neither is particularly useful.
* `spawn` is already what Windows uses, so it's known to work.

So instead of an extra knob to disable a broken-by-default feature, this just uses a correct-by-default and consistent-across-platforms default, with no knob to turn it off.

2022-07-07 04:27 UTC, auvipy requested changes
thanks for tackling this, would you please add some tests for this?

2022-07-07 18:14 UTC, itamarst commented
Will do!

2022-07-07 21:43 UTC, itamarst commented
OK, I've updated with tests, and making it actually work :grin: (all existing tests used mock, to my surprise).

2022-07-08 05:08 UTC, auvipy requested changes
one failure
  =========================== short test summary info ===========================
  FAILED t/unit/concurrency/test_asynpool.py::test_AsynPool::test_subprocesses_are_spawned
  = 1 failed,

2022-07-08 15:59 UTC, auvipy commented
also check the integration tests failures please

2022-07-09 00:44 UTC, itamarst commented
Will do.

2022-07-09 18:56 UTC, itamarst commented
Oops apparently I ran integration tests in previous testing but not at the right time after I got the right code path sorted. And indeed, it does not work. And since Windows was not actually using spawn, that validation of spawn working is not available... so perhaps it degraded since it was last supported.

In order for `spawn` to fail where `fork` succeeds, something must be wrong somewhere. Potential sites include:

1. Code running in the child worker relies on class or module-level state set in the parent process _before_ it was forked.
2. There's a bug in Billiard's `spawn` codepaths. Seems less likely?
3. Something involving file descriptor inheritance? And Python sets FD_CLOEXEC or Windows equivalent so that `execve()` (but not `fork()`!) closes file descriptors: https://peps.python.org/pep-0446/

Anything else?

2022-07-09 19:02 UTC, itamarst commented
Interestingly the first task (`ping` typically in tests) does succeed...

2022-07-09 20:33 UTC, itamarst commented
So I noticed billiard used to have a C extension that was supposedly required for execve mode to work. Is the extension module no longer necessary, or was it just not maintained, or something else? It's disabled on Python 3: https://github.com/celery/billiard/blob/master/setup.py#L232

2022-07-09 20:34 UTC, itamarst commented
(here's the reference to it being necessary for execv: https://github.com/celery/billiard/blob/master/setup.py#L33)

2022-07-10 06:19 UTC, auvipy commented
also upgrading/syncing the billiard codes is a long overdue

2022-07-10 18:00 UTC, itamarst commented
Here we can see some logs where the first task (`ping`) succeeds. But then there's a kombu error; the second task does not succeed:

```
INFO     celery.worker.consumer.connection:connection.py:22 Connected to amqp://guest:**@127.0.0.1:5672//
INFO     celery.worker.strategy:strategy.py:161 Task celery.ping[83f98219-6663-458c-bd01-437091802b4b] received
[2022-07-10 13:57:23,212: INFO/SpawnPoolWorker-2] child process 834713 calling self.run()
[2022-07-10 13:57:23,283: INFO/SpawnPoolWorker-2] Task celery.ping[83f98219-6663-458c-bd01-437091802b4b] succeeded in 0.025449884007684886s: 'pong'
ERROR    kombu.pidbox:pidbox.py:106 pidbox command error: AttributeError("'NoneType' object has no attribute 'groups'")
Traceback (most recent call last):
  File "/home/itamarst/devel/celery/.tox/3.7-integration-rabbitmq/lib/python3.7/site-packages/kombu/pidbox.py", line 102, in dispatch
    reply = handle(method, arguments)
  File "/home/itamarst/devel/celery/.tox/3.7-integration-rabbitmq/lib/python3.7/site-packages/kombu/pidbox.py", line 124, in handle_cast
    return self.handle(method, arguments)
  File "/home/itamarst/devel/celery/.tox/3.7-integration-rabbitmq/lib/python3.7/site-packages/kombu/pidbox.py", line 118, in handle
    return self.handlers[method](self.state, **arguments)
  File "/home/itamarst/devel/celery/celery/worker/control.py", line 275, in enable_events
    if dispatcher.groups and 'task' not in dispatcher.groups:
AttributeError: 'NoneType' object has no attribute 'groups'
```

Any idea what might cause that, and any sense if it's related?

2022-08-18 09:23 UTC, thedrow commented
> So I noticed billiard used to have a C extension that was supposedly required for execve mode to work. Is the extension module no longer necessary, or was it just not maintained, or something else? It's disabled on Python 3: https://github.com/celery/billiard/blob/master/setup.py#L232

Billiard itself needs a maintainer who knows what he's doing. The C extension, like every other component in billiard receives very little attention.

2022-08-26 16:57 UTC, xboy2k11 commented
@itamarst Good day, sir.  We have had this same issue with celery in several different applications over the years. I last solved it with the spawn fix, but that's no longer an option since airflow needs a newer version of celery.  We would be happy to help test this at scale once you're confident the PR is complete.

2022-10-27 13:59 UTC, itamarst commented
Unfortunately I don't have time to work on this at the moment, so if someone else wants to take it up let me know.

2022-11-30 09:01 UTC, ShaheedHaque commented
> also upgrading/syncing the billiard codes is a long overdue

Is there some information - or documentation - on what Billiard actually *does*? What was/is the rationale for replacing multiprocessing?

2022-12-13 00:17 UTC, sabetAI commented
@itamarst I get a weird crash, and the following warning when trying to run celery with your PR:

/home//miniconda3/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown

Any ideas why?

2022-12-13 02:57 UTC, itamarst commented
@sabetAI I never got this to working state, sorry... Will close to prevent confusion. Still would be nice if someone could figure out how to do this.

2022-12-13 02:57 UTC, closed without merging

2022-12-13 03:02 UTC, sabetAI commented
@itamarst no worries. Do you have a dockerfile I can use to reproduce?

2022-12-13 08:23 UTC, ShaheedHaque commented
FWIW, I would love to see this taken forward. It seems clear that this core fork-versus-spawn functionality of Celery is broken in multiple use cases and with a variety of hard-to-track down symptoms, but it also seems clear that no one person has the knowledge+willingness to drive this to conclusion. Might it be possible to draw together a small group to work on this in some collaborative fashion?

2022-12-13 16:29 UTC, sabetAI commented
@ShaheedHaque @itamarst yes! In particular, Celery multi-processing doesn't play well with CUDA. Know any fixes?

2022-12-13 16:53 UTC, auvipy commented
I am not sure celery multiprocessing was designed to work with CUDA. you should try Dask / Ray for that I think

2022-12-15 12:53 UTC, adampl commented
It does work with CUDA, you just have to make 100% sure that no CUDA code is executed by the root (parent) process :)

2022-12-20 01:00 UTC, sabetAI commented
@adampl interesting, can you share a link so I can read up further on that? Do I disable CUDA on parent by running torch code only if os.getpid != os.getppid()?

2022-12-20 11:21 UTC, adampl commented
I just import all the CUDA-related stuff inside the task functions. The trick with PIDs may work too. That way no CUDA context is ever initialized in the parent process. I also use the Celery Max Tasks Per Child=1 setting so that the child process is deleted when the task is finished, to ensure full cleanup.

2023-02-15 22:20 UTC, veonua commented
>  deleted when the task is finished, to ensure full cleanup.

some models are 10+ Gb, sometimes it can be very costly to do cleanup after every task

2023-02-19 22:25 UTC, adampl commented
> sometimes it can be very costly to do cleanup after every task

Yes, but unfortunately many libraries don't properly manage GPU resources, causing subsequent tasks to fail.

2025-07-09 07:00 UTC, auvipy commented
hey good peoples! we got a new approach here to fix it https://github.com/celery/celery/pull/9810 . please check it out