Added integration test test_chain_freezing_a_chord_should_freeze_the_group_id()
celery/celery pull request #7692
Opened 2022-08-07 16:34 UTC by Nusnus

This test should validate that when using a frozen chain in different workers, it would duplicate the group id of the group in the frozen chain and will not generate a new group id for each worker (because it is supposed to be frozen)

2022-08-08 03:26 UTC, auvipy requested changes
thanks for the integration test. can you also try to fix the integration test failures in CI?

2022-08-08 07:13 UTC, thedrow commented
@auvipy Could you please review the pull request **and** the build log before you make any comments regarding the quality of the PR or the state of the build?

If you were to check the build output, you'd find that the test @Nusnus contributed is failing. The next logical question is why would he contribute a failing test. That's because we have a test case for something that's currently not working in Celery. The next logical question is why this test case doesn't work.
I appreciate your contributions, but at this point we might as well create a Github Action that reminds contributors of what needs to be done. If you don't know what to do, you can always ask.

2022-08-08 16:57 UTC, auvipy commented
@thedrow, I used to check codes and logs before commenting in most of the time. however, for this PR, reading the PR description, and seeing all the integration tests failing, I wasn't able to understand initially it was just a failing test :) 

I have asked the contributor if he is up for fixing the failing codes. So from my point of view, this is not a big issue. And for the new contributors action, that would be a good stuff to get rid of lots of manual verification.

2022-08-14 17:05 UTC, thedrow approved these changes

2022-08-14 17:05 UTC, merged