Added test for chord stamping with a chord body type
celery/celery pull request #7730
Opened 2022-08-28 15:53 UTC by Nusnus

2022-08-29 14:59 UTC, thedrow requested changes
Just a minor comment and we're ready to go.

2022-08-29 14:59 UTC, thedrow commented on t/unit/tasks/test_canvas.py
> +                return reduce(operator.mul, numbers)
```suggestion
                #  TODO: Drop this backport once
                #              we drop support for Python 3.7
                import operator
                from functools import reduce

                return reduce(operator.mul, numbers)
```

2022-08-29 15:22 UTC, Nusnus commented on t/unit/tasks/test_canvas.py
> +                return reduce(operator.mul, numbers)
Done @thedrow

2022-08-30 03:51 UTC, auvipy approved these changes

2022-08-30 03:51 UTC, merged