Fix beat Service __reduce__ error
celery/celery pull request #7739
Opened 2022-09-02 07:25 UTC by AXHMFHNP

Fix beat Service `__reduce__` error

2022-09-02 11:32 UTC, auvipy reviewed
can you please tell what error you are fixing with this?

2022-09-02 12:06 UTC, AXHMFHNP commented
“TypeError: 'Celery' object is not callable” reported at celery beat service start.
```
        debug('beat: Ticking with max interval->%s',
              humanize_seconds(self.scheduler.max_interval))
```
self.scheduler.max_interval -> self.scheduler -> self.get_scheduler() 
```
        return symbol_by_name(self.scheduler_cls, aliases=aliases)(
```
 self.scheduler_cls becomes Celery object due to the inconsistency between the order of `__init__` parameters and the order returned by `__reduce__`

2022-09-05 03:43 UTC, AXHMFHNP commented
Done

2022-09-05 04:14 UTC, auvipy requested changes

2022-09-05 04:14 UTC, auvipy commented on t/unit/test_beat.py
> +        s2 = pickle.loads(pickle.dumps(s1))
why specifically pickle? can we also try json here beside pickle?

2022-09-05 09:01 UTC, AXHMFHNP commented
The problems that occurred with the old version are not reproduced in the new version.

2022-09-05 09:01 UTC, closed without merging