Add --skip-checks flag to bypass django core checks
celery/celery pull request #7859
Opened 2022-10-28 16:37 UTC by mudetz

## Description

Resolves feature request #7581

2022-10-29 03:38 UTC, auvipy requested changes

2022-10-29 03:38 UTC, auvipy commented on docs/whatsnew-5.2.rst
> +
this will be added to v5.3.0, so this part should be removed and find a location in CLI part of the doc

2022-11-03 06:53 UTC, auvipy requested changes
we should have this new command flag documented here
https://docs.celeryq.dev/en/stable/reference/cli.html or look for appropriate place to describe the new command with versionadded 5.3 notation

2022-11-03 14:04 UTC, mudetz commented
> we should have this new command flag documented here https://docs.celeryq.dev/en/stable/reference/cli.html or look for appropriate place to describe the new command with versionadded 5.3 notation

It is documented automatically in the CLI reference: https://celery--7859.org.readthedocs.build/en/7859/reference/cli.html

2022-11-03 15:29 UTC, merged