StampingVisitor will _visit_ the callbacks and errbacks of the signature
celery/celery pull request #7867
Opened 2022-10-31 13:55 UTC by Nusnus

When a signature is stamped, this will allow the visitor to also stamp the signature's link and link_error callbacks automatically if they exists before the stamping

2022-10-31 15:07 UTC, thedrow requested changes
This needs more tests and documentation.
There are only minor issues I'd like to resolve.

2022-10-31 15:07 UTC, thedrow commented on celery/canvas.py
> +            _merge_dictionaries(headers, visitor_headers or {})
When will `visitor_headers` be a falsy value?
528 checks if it isn't so why `or {}` is necessary?

2022-10-31 15:07 UTC, thedrow commented on t/unit/tasks/test_canvas.py
> +        c.tasks[-1].options['link'][0].options.clear()  # remove stamped headers from link
Why do we need this?

2022-10-31 15:07 UTC, thedrow commented on celery/canvas.py
> +        additional_headers = headers.copy()
Can we find a more meaningful name?

2022-11-02 15:05 UTC, Nusnus commented on celery/canvas.py
> +        additional_headers = headers.copy()
Fixed

2022-11-02 15:08 UTC, Nusnus commented on t/unit/tasks/test_canvas.py
> +        c.tasks[-1].options['link'][0].options.clear()  # remove stamped headers from link
Fix Pushed @thedrow

2022-11-02 17:29 UTC, Nusnus commented
Added doc to feature

2022-11-03 09:58 UTC, thedrow approved these changes
LGTM

2022-11-03 09:58 UTC, merged