Support for out-of-tree worker pool implementations
celery/celery pull request #7880
Opened 2022-11-05 21:09 UTC by ShaheedHaque

## Description

At the moment, Celery has a fixed notion of the worker pool types it supports. This PR introduces the the possibility of an out-of-tree worker pool implementation. Supporting commits ensure that the current worker pool implementations consistently call into `BasePool._get_info()`, and enhance it to report the work pool class in use via the "celery inspect stats" command. For example:
```
$ celery -A ... inspect stats
->  celery@freenas: OK
    {
        ...
        "pool": {
           ...
            "implementation": "celery_aio_pool.pool:AsyncIOPool",
```
It is used as follows:

- Set the environment variable CELERY_CUSTOM_WORKER_POOL to the name of
        an implementation of :class:`celery.concurrency.base.BasePool` in the
        standard Celery format of "package:class".

- Select this pool using '--pool custom'.

I've not added end-user docs as this can be considered an enabling step for #7874, but would be happy to draft something if required (and a suitable place in the docs is pointed out).

2022-11-13 13:54 UTC, thedrow requested changes
Please adjust unit tests and ensure they pass

2022-11-13 21:18 UTC, ShaheedHaque commented
> Please adjust unit tests and ensure they pass

I adjusted the affected unit tests, and they now pass. Did I miss some? Or are you requesting unit tests for the new functionality?

2022-11-14 05:48 UTC, auvipy commented
> > Please adjust unit tests and ensure they pass
> 
> I adjusted the affected unit tests, and they now pass. Did I miss some? Or are you requesting unit tests for the new functionality? If so, then I would say that adding the reporting of the selected pool in the inspect command output covers at least that part, and by definition it is difficult to add extra coverage for something out of tree.
> 
> Nevertheless, if you have any specific ideas, I am happy to try to address them.

the CI is still failing, you might forgot to push your fixes? he was mainly asking about fixing the current tests of CI which were failing due to proposed changes

2022-11-15 03:24 UTC, ShaheedHaque commented
@thedrow @auvipy Two tests I broke are now fixed; apologies for not having spotted them myself.

2022-11-15 06:37 UTC, auvipy approved these changes

2022-11-15 06:38 UTC, merged

2022-11-15 06:39 UTC, auvipy commented
thanks for improving the overall tests as well on another PR.