Type annotations for `celery/utils/text.py`
celery/celery pull request #8107
Opened 2023-03-04 17:56 UTC by max-muoto

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

2023-03-04 18:06 UTC, max-muoto commented on celery/utils/text.py
> -        return f'{{{sep} {pformat(value, 4, nl_width)[1:]}'
Syntax error here.

2023-03-04 19:16 UTC, Nusnus commented
There are some issues with the CI so the tests aren't running correctly.
I will handle this soon, FYI

2023-03-04 19:27 UTC, max-muoto commented
> There are some issues with the CI so the tests aren't running correctly. I will handle this soon, FYI

Sounds good, thanks!

2023-03-04 20:23 UTC, Nusnus commented
The failure is real: https://github.com/celery/celery/actions/runs/4332357772/jobs/7565145570#step:8:1002

2023-03-04 20:24 UTC, Nusnus commented
```celery/utils/text.py:50: in <module>
      def join(l: list[str], sep: str = '\n') -> str:
  E   TypeError: 'type' object is not subscriptable```

2023-03-04 20:32 UTC, max-muoto commented
> ```
>       def join(l: list[str], sep: str = '\n') -> str:
>   E   TypeError: 'type' object is not subscriptable```
> ```

My bad there, just fixed!

2023-03-04 21:33 UTC, Nusnus commented
```ERROR t/unit/bin/test_beat.py - NameError: name 'Match' is not defined
[1068](https://github.com/celery/celery/actions/runs/4332762108/jobs/7565753809#step:8:1069)
  ERROR t/unit/bin/test_worker.py - NameError: name 'Match' is not defined```

2023-03-05 00:51 UTC, max-muoto commented
> ```
> ERROR t/unit/bin/test_beat.py - NameError: name 'Match' is not defined
> ERROR t/unit/bin/test_worker.py - NameError: name 'Match' is not defined
> ```

Ah forgot to quote that, as it should be since it's conditionally imported if type checking is enabled. Fixed.

2023-03-05 06:09 UTC, auvipy requested changes

2023-03-05 06:09 UTC, auvipy commented on celery/utils/text.py
>  """Text formatting utilities."""
```suggestion
"""Text formatting utilities."""
from __future__ import annotations
```

2023-03-05 08:33 UTC, auvipy approved these changes

2023-03-05 08:47 UTC, merged