fix: add expire string parse.
celery/celery pull request #8134
Opened 2023-03-17 06:31 UTC by Bidaya0

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

try to fix https://github.com/celery/celery/issues/8128.

2023-03-17 09:41 UTC, auvipy requested changes
and also check build failures for existing tests

2023-03-22 16:47 UTC, Bidaya0 commented on celery/app/base.py
> +            if isinstance(expires, str):
> please also validate the change with tests

Tests have been added in t/unit/app/test_app.py

2023-03-23 08:17 UTC, merged

2023-03-23 08:17 UTC, auvipy commented
thank you

2023-06-08 09:45 UTC, mililic85 commented
Hi, I have encountered the same error while using Celery primitives on my code.
Can you please advise me on how to check the Celery version in which this merge was impacted? I would like to see if this merge fixes my code. 
Celery used for me is version 5.2.7 in Python 10.5. 
Thanks a lot.

2023-06-08 10:59 UTC, auvipy commented
you can see it is in 5.3.0 release milestone, you can try celery==5.3.0