chore(style): switch to Ruff
celery/celery pull request #8234
Opened 2023-05-07 18:08 UTC by stegayet

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

This PR aims at showcasing switching from multiple pre-commit tools (flake8, isort, yesqa, pyupgrade and bandit) to [Ruff](https://beta.ruff.rs/docs/). More precisely, it:
- adds ruff to pre-commit configuration
- adds ruff section in `pyproject.toml`

This is left as a draft for now as I want to get feedback on whether we want to go for this switch or not, if the idea is accepted, I'll describe in further details the changes and split the work in multiple commits/PRs.

Advantages:
- Ruff is way quicker than former tools ([numbers speak for themselves](https://beta.ruff.rs/docs/)) .
- We can leverage even more `pyproject.toml` configuration and maybe at some point get rid of `setup.cfg` file.

2023-05-08 20:12 UTC, Nusnus commented
I'd happily supervise this PR, but I want your opinion @thedrow @auvipy first.
Last time I checked Ruff was long ago, and it appears there have been some advancements since.

I am willing to give it another shot, but as I said in the Poetry PR - I think it would be wise to have a more wide upgrade of such change - can you handle the scope? @stegayet

2023-05-08 23:58 UTC, stegayet commented
Sure :+1: 
I'll check related repositories and do the same proposal.

2023-05-09 04:22 UTC, auvipy commented
we should postpone effort on this for now

2023-05-15 03:30 UTC, auvipy requested changes
I think we should not consider ruff now. lets keep the tools here as is

2023-05-15 03:31 UTC, auvipy commented
I'm open to move to poetry though

2023-05-15 03:31 UTC, closed without merging