Class method to process crontab string
celery/celery pull request #8250
Opened 2023-05-14 20:53 UTC by padgy

Convenience method for creating a crontab object from a string. Many configurations in systems are written as a cron string, so adding a helper function for this would make reading schedules easier.

2023-05-15 02:27 UTC, auvipy requested changes
I would like to know more context and examples and unit tests for the proposed change

2023-06-07 11:48 UTC, auvipy commented
we need proper unit tests for considering that, also wait for feedback from more users

2024-03-26 07:55 UTC, jayeff reviewed
I too think having a convenience method to get a `crontab` from a cron expression would be helpful in cases where you use configration (e.g. enviroment variable) to define a schedule for some tasks. We use this quite a lot to have different schedules for different runtime enviroments

I would suggest to use the official cron format though as per suggestion

@auvipy In case you give a go ahead I could update the format and add some unit tests to this PR so that it can be merged

2024-03-26 07:55 UTC, jayeff commented on celery/schedules.py
> +        minute, hour, day_of_week, day_of_month, month_of_year = crontab.split(" ")
I would suggest to switch the order of fields to match offical cron format
```suggestion
        minute, hour, day_of_month, month_of_year, day_of_week = crontab.split(" ")
```

```
# ┌───────────── minute (0–59)
# │ ┌───────────── hour (0–23)
# │ │ ┌───────────── day of the month (1–31)
# │ │ │ ┌───────────── month (1–12)
# │ │ │ │ ┌───────────── day of the week (0–6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * * <command to execute>
```
Source: https://en.wikipedia.org/wiki/Cron

2024-05-26 06:57 UTC, auvipy commented
> @auvipy In case you give a go ahead I could update the format and add some unit tests to this PR so that it can be merged

sorry for the late response. Please give it a shot if you can!

2024-06-15 12:59 UTC, Nusnus requested changes
Please also take note of the failing lint error:
```console
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

celery/schedules.py:415: error: Function is missing a return type annotation  [no-untyped-def]
Found 1 error in 1 file (checked 10 source files)
```

Thank you 🙏

2024-06-18 09:58 UTC, jayeff commented
I created a new PR https://github.com/celery/celery/pull/9079 which include tests and fixes the mypy error

2024-06-19 08:07 UTC, closed without merging

2024-06-19 08:07 UTC, Nusnus commented
Thank you @padgy for the original contribution ♥️
It was finished and merged here: https://github.com/celery/celery/pull/9079