Fix backend.get_task_meta ignores the result_extended config parameter in mongodb backend
celery/celery pull request #8391
Opened 2023-07-25 09:32 UTC by ycc140

Fix for bug report: #8387.

backend.get_task_meta ignores the result_extended config parameter in mongodb backend

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

2023-07-25 12:53 UTC, auvipy requested changes

2023-07-26 04:02 UTC, auvipy requested changes

2023-07-26 04:02 UTC, auvipy commented on celery/backends/mongodb.py
> +                return self.meta_from_decoded({
you can check this file https://github.com/celery/celery/blob/main/t/unit/backends/test_mongodb.py and other back end tests in https://github.com/celery/celery/blob/main/t/unit/backends/ folder

2023-07-26 08:22 UTC, ycc140 commented on celery/backends/mongodb.py
> +                return self.meta_from_decoded({
Thanks for the pointers. I have added a new test case, It works on my laptop :-)

2023-07-26 13:17 UTC, auvipy commented
thanks lets wait for the CI

2023-07-27 13:50 UTC, ycc140 commented
So did it pas CI processing? Is there anything else that I have to do?

2023-07-28 05:57 UTC, auvipy commented
CI is passing

2023-07-28 05:58 UTC, auvipy approved these changes

2023-07-28 06:00 UTC, merged

2023-07-28 06:00 UTC, auvipy commented
thanks