Fix #8431: Set format_date to False when calling _get_result_meta on mongo backend
celery/celery pull request #8432
Opened 2023-08-10 14:27 UTC by asukero

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

This PR set `format_date` argument to `False` when calling `self.get_result_meta` in `MongoBackend._strore_result` to fix task_result collection never been cleaned up when task_expires configuration is set.

Fixes #8431

2023-08-11 16:15 UTC, asukero commented
Since MongoDB queries are mocked inside `test_mongodb.py`, I can't verify that `date_done` is inserted as `ISODate` inside task_result collection instead of string but I added a testcase on `test_base.py` on `get_result_meta` with `format_date`.

I hope it's good for you :slightly_smiling_face:

2023-08-12 14:05 UTC, Nusnus commented
@asukero 
```
pyupgrade................................................................Passed
flake8...................................................................Failed
- hook id: flake8
- exit code: 1

t/unit/backends/test_base.py:190:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`
t/unit/backends/test_base.py:201:16: E721 do not compare types, for exact checks use `is` / `is not`, for instance checks use `isinstance()`

Strip unnecessary `# noqa`s..............................................Passed
check for merge conflicts................................................Passed
check toml...............................................................Passed
check yaml...............................................................Passed
mixed line ending........................................................Passed
isort....................................................................Passed
mypy.....................................................................Passed
```

2023-08-13 05:52 UTC, auvipy requested changes
can you please fix the lint error?

2023-08-16 07:48 UTC, asukero commented
Lint error fixed, sorry for the delay

2023-08-16 09:43 UTC, Nusnus commented
The test failures are in `test_chain.test_nested_chain_group_lone`, this is something that started yesterday and 1) has nothing to do with this PR, 2) appears not to be related to any recent code changes a.k.a something external.

I'll ignore it reviewing this PR then, @auvipy FYI

2023-08-16 11:41 UTC, Nusnus approved these changes

2023-08-16 11:41 UTC, merged