Use string value for CELERY_SKIP_CHECKS envvar
celery/celery pull request #8462
Opened 2023-08-29 14:07 UTC by jennifer-richards

## Description

Sets the `CELERY_SKIP_CHECKS` value to a string value (`'true`) instead of a Boolean. Updates the existing test to patch in this string value instead of `True`

An integration test that validates that command line argument handling in `celery/bin/celery.py` matches the unit test assumptions would be a nice addition. However, since it should test more than just this option, it is far enough afield that I have not added it.

Fixes #8461.

2023-08-30 07:25 UTC, auvipy reviewed
approving on principle. but are we sure we don not have any other edge case?

2023-08-30 15:38 UTC, jennifer-richards commented
> approving on principle. but are we sure we don not have any other edge case?

Is there a particular edge you're concerned about?

As I mentioned, if I understand the tests correctly, there is a fairly glaring shortcoming: there's no test that the `--skip-checks` option to the cli utility feeds the expected value into `CELERY_SKIP_CHECKS` in the environment. In fact, there's no test at all that the `--skip-checks` option doesn't entirely crash the utility (which it, in fact, did prior to this patch).

There's also something between a bug and a lack of documentation about the `CELERY_SKIP_CHECKS` variable. The documentation for it says, generically, "Provide a default value..." without any mention of how the value is interpreted. Any truthy value (i.e., non-empty string) is interpreted as "skip the initial checks."  I hesitated to use the value `'true'` here because that falsely suggests that setting `CELERY_SKIP_CHECKS=false` might disable it. (IMO a check similar to the `strtobool()` utility in the serializer code would be ideal, but a quick scan of the code base found at least one other place where the simpler truthiness check was applied to an environment variable used as a flag.)

I'd be happy to capture these as tickets, but imo they're substantive enough that I didn't want to start addressing them as a drive-by. Someone more involved in the project needs to think about them.

2023-08-31 06:14 UTC, auvipy commented
should we at least correct some of the doc issues in this PR? I am OK to merge this soon

2023-08-31 17:47 UTC, jennifer-richards commented
Sure. I think the `Provide a default for --skip-checks` is coming from `sphinx-click` and I don't see a way to adjust that. Instead, I've added text to the `--skip-checks` help that should make it clear.

I'm going to separately push a minor tweak to the CLI documentation to point out that the environment variables all need a `CELERY_` prefix.

2023-09-01 08:29 UTC, auvipy requested changes
we need to fix the lint errors and possible some additional test case to improve the test coverage. can you please put some effort on that?

2023-09-01 15:47 UTC, jennifer-richards commented
I think that should eliminate the lint and improve the coverage.

2023-09-01 16:04 UTC, jennifer-richards commented
Tests appear to be failing, but it's not clear to me why. If there's something specific to be done please let me know but I'm at the limit of my familiarity with the project and my time available to debug.

2023-09-02 10:28 UTC, auvipy approved these changes

2023-09-02 10:30 UTC, merged