Make custom remote control commands available in CLI
celery/celery pull request #8489
Opened 2023-09-07 13:46 UTC by tobinus

Fixes #6608 

## Description

The `celery inspect COMMAND` and `celery control COMMAND` CLI subcommands let users run remote commands against any currently running worker. However, you were limited to running the remote control commands that were pre-defined with Celery. Any custom inspect or control commands specified by the user would be rejected.

The reason for this is the fact that the Click configuration is done at import-time. The user's custom inspect and control commands had yet to be registered by the time the top-level code in the `celery/bin/control.py` module was evaluated.

This pull request:
* Moves the validation of the remote control command name from Click to our own code, at which point the user's custom remote control commands have been registered
* Adds a `--list` option for seeing all available remote control commands of the relevant type, along with their signature and help summary
* Adds unit tests for verifying that the `inspect` and `control` CLI subcommands accept custom remote control command names and the `--list` option

I have not been able to find a way to run the tests successfully on my computer, so I'll need to use the GitHub Actions workflow to help me test.

2023-09-07 13:54 UTC, tobinus commented
@auvipy Here's a draft pull request for fixing #6608, as per [your comment there](https://github.com/celery/celery/issues/6608#issuecomment-1678671936). (It may be a bit more finalized than "proof of concept", though, haha)

2023-09-07 15:06 UTC, Nusnus commented
@tobinus 
> I have not been able to find a way to run the tests successfully on my computer, so I'll need to use the GitHub Actions workflow to help me test.

What troubles did you have running the tests locally?

2023-09-08 07:36 UTC, tobinus commented
@Nusnus 
> What troubles did you have running the tests locally?

Thank you for asking! I couldn't get the Docker image to build, using Podman. It fails on [this step](https://github.com/celery/celery/blob/main/docker/Dockerfile#L78-L80) due to `OSError: [Errno 18] Invalid cross-device link: '/home/developer/.pyenv/versions/3.8.18/lib/python3.8/site-packages/pip/' -> '/home/developer/.pyenv/versions/3.8.18/lib/python3.8/site-packages/~ip'`. As far as I can tell, this is a kernel bug or a Podman bug, so I'm stuck. I did find a [bug report in Podman](https://github.com/containers/podman/issues/13123), but that should have been fixed already.

As for running them locally: I thought there was something wrong with my setup, since the tests just end up hanging at `t/unit/bin/test_worker.py::test_cli`. But they do that in GitHub Actions as well. I have no idea why that is, I haven't touched that file at all. The tests I wrote all pass when I run them alone, but some of them fail when running them alongside the other tests, so there seems to be some issues with state carrying over between tests.

2023-09-08 08:23 UTC, tobinus commented
The worker in `t/unit/bin/test_worker::test_cli` ended up ignoring the configured broker settings when the `test_control.py` had run beforehand. I think this is caused by celery modifying `os.environ` when it is given the command line option `--broker memory://`. I fixed this issue by resetting `os.environ` after the new tests.

Now on to the problem of why additional command line parameters are being sent when I run all the tests. It is possible to work around this problem by adding `**kwargs` as a parameter for `control`, just like `inspect` already has, but I'd like to understand the problem a bit better.

2023-09-08 12:49 UTC, tobinus commented
Ok, I see the problem. The `t/unit/app/test_preload_cli.py` test uses `app.user_options['preload']`. When it does, [Celery adds those options to the function objects themselves](https://github.com/celery/celery/blob/1aff856ea37a477639ef2c8883f121d6670f72e0/celery/bin/celery.py#L166-L172):

```python
    # User options
    worker.params.extend(ctx.obj.app.user_options.get('worker', []))
    beat.params.extend(ctx.obj.app.user_options.get('beat', []))
    events.params.extend(ctx.obj.app.user_options.get('events', []))

    for command in celery.commands.values():
        command.params.extend(ctx.obj.app.user_options.get('preload', []))
```

`worker.params`, `beat.params`, `events.params` and `*.params` are all global state, and are _not_ reset between the tests. So the issue I'm seeing is two-fold:

1. The preload test makes changes to global state that carry over to all later tests. I have an idea of how to fix that.
2. If the user specifies preload options, subcommands may end up not working if they're not equipped with `**kwargs`. So the test failure may showcase a real bug?

I could probably just add `**kwargs` to `command`'s argument list, but it feels a bit fragile to require that all Click subcommands should accept `**kwargs`.

2023-09-08 13:55 UTC, tobinus commented
The tests should run now. However, if you define your own `app.user_options['preload']`, you won't be able to run `celery control ...` since it does not have `**kwargs` in its argument list. Sometime next week, I'll look into which solution is better:

1. Modify `celery.bin.base.handle_preload_options` so that it doesn't pass preload options along to the decorated function, eliminating the need for `**kwargs` (except for the commands that accept user options outside of the preload options)
2. Keep the requirement that all Celery subcommands must accept `**kwargs`, and add it to any subcommands currently missing it (like `control`)

I'm currently leaning towards solution 1.

2023-09-09 07:36 UTC, auvipy requested changes
thanks for handling this and refactoring the old tests. My primary concern here is if we are  changing any existing behavior or functionality to implement the new one or fix anything, we need to be very careful about that. Might also need to consider splitting the relevant changes if needed. I will need some time to thoroughly check and review it.

2024-01-17 10:38 UTC, dejlek commented
This is superimportant for me as my custom inspect/control commands are not working since Celery moved to Click... :(

2024-01-17 18:10 UTC, auvipy commented
We are considering it for 5.4 release. Can you try and review ut

2024-01-22 10:33 UTC, dejlek commented
> My primary concern here is if we are changing any existing behavior or functionality to implement the new one or fix anything, we need to be very careful about that.

I wish you did have this concern when decision was made to switch to Click...

2024-01-22 11:54 UTC, Nusnus commented
> > My primary concern here is if we are changing any existing behavior or functionality to implement the new one or fix anything, we need to be very careful about that.
> 
> I wish you did have this concern when decision was made to switch to Click...
> 
> 

Cutting away the context does not remove it. He was referring to the changes of this PR, so it's a bit misleading my friend.

The change to Click had its winning arguments at the time, so the most useful attitude now is to just keep moving forward.

We do heavily consider meaningful changes but we can't please everyone at the same time so it's better to adjust the expectations instead.

2024-01-23 09:41 UTC, auvipy commented
> > My primary concern here is if we are changing any existing behavior or functionality to implement the new one or fix anything, we need to be very careful about that.
> 
> I wish you did have this concern when decision was made to switch to Click...

well, yes we have lot of issues in the implementation TBH, but design wise it was a good move. actually we need to work on making it parity with old features so. so i request having bit more patience and also if you please collaborate in that, that will be really helpful. but thanks for raising the issue.

2024-02-28 14:50 UTC, merged

2024-03-08 20:01 UTC, fekete42 commented
Hi,

I've faced this issue recently.  I think I managed to find a relatively simple solution. I think the root cause of the problem is that options obtained from Panel.meta are extracted when the module celery.bin.control is loaded, not when it's used. 

My idea would be to define a new type, which returns the proper custom control commands dynamically:

```
from click.types import ParamType

class PanelMetaChoiceType(ParamType):
    """Panel meta option."""

    name = "panel_meta_choice"

    def convert(self, value, param, ctx):
        return click.Choice([name for name, info in Panel.meta.items()
                             if info.type == 'inspect' and info.visible]).convert(value, param, ctx)

PANEL_META_CHOICE_TYPE = PanelMetaChoiceType()

....

@click.command(cls=CeleryCommand,
               context_settings={'allow_extra_args': True})
@click.argument("action", type=PANEL_META_CHOICE_TYPE )
@click.option('-t',
              '--timeout',
              cls=CeleryOption,
              type=float,
              default=1.0,
              help_group='Remote Control Options',
              help='Timeout in seconds waiting for reply.')
@click.option('-d',
              '--destination',
              cls=CeleryOption,
              type=COMMA_SEPARATED_LIST,
              help_group='Remote Control Options',
              help='Comma separated list of destination node names.')
@click.option('-j',
              '--json',
              cls=CeleryOption,
              is_flag=True,
              help_group='Remote Control Options',
              help='Use json as output format.')
@click.pass_context
@handle_preload_options
def inspect(ctx, action, timeout, destination, json, **kwargs):
    """Inspect the worker at runtime.
...
...

```

I hope you still use this idea useful even if this came a bit late.

Best regards,
Attila

2024-03-12 11:21 UTC, auvipy commented
@fekete42 can you open a draft PR, attila?