Document gevent concurrency
celery/celery pull request #8520
Opened 2023-09-19 17:10 UTC by cunla

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description
Add documentation for gevent, following [this issue](https://github.com/celery/celery/issues/8425#issuecomment-1701058121)

2023-09-20 03:32 UTC, auvipy requested changes

2023-09-20 03:32 UTC, auvipy commented on docs/userguide/concurrency/gevent.rst
> +You can enable the Eventlet pool by using the
```suggestion
You can enable the gevent pool by using the
```

2023-09-20 03:32 UTC, auvipy commented on docs/userguide/concurrency/gevent.rst
> +You can enable the Eventlet pool by using the
Eventlet pool or gevent pool?

2023-09-20 22:16 UTC, Nusnus approved these changes

2023-09-20 22:32 UTC, Nusnus commented
Great addition to the docs!
Well done 💯 - liked the links to the known issues, useful.

Thank you! @cunla

2023-09-21 03:16 UTC, auvipy requested changes

2023-09-21 03:16 UTC, auvipy commented on docs/userguide/concurrency/gevent.rst
> +
```suggestion
```

2023-09-21 03:16 UTC, auvipy commented on docs/userguide/concurrency/gevent.rst
> +
```suggestion
```

2023-09-21 03:16 UTC, auvipy commented on docs/userguide/concurrency/gevent.rst
> +
```suggestion
```

2023-09-21 03:16 UTC, auvipy commented on examples/gevent/README.rst
> +
```suggestion
```

2023-09-21 03:20 UTC, auvipy approved these changes

2023-09-21 03:20 UTC, merged