feat(daemon): allows daemonization options to be fetched from app settings
celery/celery pull request #8553
Opened 2023-10-03 15:45 UTC by noirbizarre

## Description

This pull-requests allows to provide daemonization settings (`--logfile`, `--pidfile`, `--uid`, `--gid`, `--umask` and `--executable`) from your config file with the following new settings:
- `beat_logfile`
- `beat_pidfile`
- `beat_uid`
- `beat_gid`
- `beat_umask`
- `beat_executable`
- `worker_logfile`
- `worker_pidfile`
- `worker_uid`
- `worker_gid`
- `worker_umask`
- `worker_executable`
- `events_logfile`
- `events_pidfile`
- `events_uid`
- `events_gid`
- `events_umask`
- `events_executable`

This PR is backward compatible, tested and documented. Missing CLI documentation for daemonization settings have been added in the process.

2023-10-03 16:40 UTC, auvipy requested changes
thanks for the PR. can you check the CI failures please?

2023-10-03 18:19 UTC, noirbizarre commented
There it is, PR fixed, Ci is all green 👍🏼 
(last `Celery / Unit 3.9` job is stuck but I'be dealing with this issue for hours: github actions cache retrieval is not in a good state, it should unlock any time)

2023-10-04 10:42 UTC, auvipy commented
What extra benefits the changes will provide?

2023-10-04 12:07 UTC, noirbizarre commented
Today, the only way to provide those values are from cli flag which prevent retrieving those values from any registry (unless you have a way to fetch those values before running those daemons and passing the processed result to the cli, which is not possible in my case).
This change allows to specify those values from settings (like most of the settings you can set on cli), meaning from Python, allowing for dynamic values (which is my use case) and any kind of preprocessing.
This also works for static settings in the case you have a templated celeryconf.py loaded with `Celery.config_from_object()` (the exact case which is tested in this PR and was not possible without this PR)

2023-10-04 16:45 UTC, auvipy commented
yeah that looks nice. I am in favor of it. Lets us wait for other maintainers to look into it. I would appreciate if in the mean time you could review this PR https://github.com/celery/celery/pull/8489

2023-11-06 12:38 UTC, thedrow requested changes
There are typos in the documentation. Please review and commit the changes.

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery events` to create/store it PID file (default to no PID file created).
```suggestion
An optional file path for :program:`celery events` to create/store its PID file (default to no PID file created).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery events` to log into (default to `stdout`).
```suggestion
An optional file path for :program:`celery events` to log into (defaults to `stdout`).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal user ID to use when events :program:`celery events` drops its privileges (default to no UID change).
```suggestion
An optional user ID to use when events :program:`celery events` drops its privileges (defaults to no UID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal group ID to use when :program:`celery events` daemon drops its privileges (default to no GID change).
```suggestion
An optional group ID to use when :program:`celery events` daemon drops its privileges (defaults to no GID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `umask` to use when :program:`celery events` creates files (log, pid...) when daemonizing.
```suggestion
An optional `umask` to use when :program:`celery events` creates files (log, pid...) when daemonizing.
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `python` executable path for :program:`celery events` to use when deaemonizing (default to :data:`sys.executable`).
```suggestion
An optional `python` executable path for :program:`celery events` to use when deaemonizing (defaults to :data:`sys.executable`).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery worker` to log into (default to `stdout`).
```suggestion
An optional file path for :program:`celery worker` to log into (defaults to `stdout`).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery worker` to create/store it PID file (default to no PID file created).
```suggestion
An optional file path for :program:`celery worker` to create/store its PID file (defaults to no PID file created).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal user ID to use when :program:`celery worker` daemon drops its privileges (default to no UID change).
```suggestion
An optional user ID to use when :program:`celery worker` daemon drops its privileges (defaults to no UID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal group ID to use when :program:`celery worker` daemon drops its privileges (default to no GID change).
```suggestion
An optional group ID to use when :program:`celery worker` daemon drops its privileges (defaults to no GID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `umask` to use when :program:`celery worker` creates files (log, pid...) when daemonizing.
```suggestion
An optional `umask` to use when :program:`celery worker` creates files (log, pid...) when daemonizing.
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `python` executable path for :program:`celery worker` to use when deaemonizing (default to :data:`sys.executable`).
```suggestion
An optional `python` executable path for :program:`celery worker` to use when deaemonizing (defaults to :data:`sys.executable`).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery beat` to log into (default to `stdout`).
```suggestion
An optional file path for :program:`celery beat` to log into (defaults to `stdout`).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal file path for :program:`celery beat` to create/store it PID file (default to no PID file created).
```suggestion
An optional file path for :program:`celery beat` to create/store it PID file (defaults to no PID file created).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal user ID to use when beat :program:`celery beat` drops its privileges (default to no UID change).
```suggestion
An optional user ID to use when beat :program:`celery beat` drops its privileges (defaults to no UID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal group ID to use when :program:`celery beat` daemon drops its privileges (default to no GID change).
```suggestion
An optional group ID to use when :program:`celery beat` daemon drops its privileges (defaults to no GID change).
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `umask` to use when :program:`celery beat` creates files (log, pid...) when daemonizing.
```suggestion
An optional `umask` to use when :program:`celery beat` creates files (log, pid...) when daemonizing.
```

2023-11-06 12:38 UTC, thedrow commented on docs/userguide/configuration.rst
> +An optionnal `python` executable path for :program:`celery beat` to use when deaemonizing (default to :data:`sys.executable`).
```suggestion
An optional `python` executable path for :program:`celery beat` to use when deaemonizing (defaults to :data:`sys.executable`).
```

2023-12-06 13:50 UTC, Nusnus approved these changes
LGTM

2023-12-06 13:53 UTC, Nusnus commented
> In addition, all those new configuration settings should be marked with `.. versionadded:: 5.4`

@noirbizarre thank you for this PR!
Please add the missing 5.4 doc, and I'll merge it right away.

2024-01-10 14:29 UTC, noirbizarre commented
Hi 👋🏼 
Sorry for the lack of response lately (overbooked, holidays, children... life). I'll read the entire thread and update the PR accordingly by the end of week (maybe tonight if the remaining tasks are quick) !

2024-01-10 15:17 UTC, Nusnus commented
> Hi 👋🏼 Sorry for the lack of response lately (overbooked, holidays, children... life). I'll read the entire thread and update the PR accordingly by the end of week (maybe tonight if the remaining tasks are quick) !

Amazing!
Tag me when you’re done and I’ll finish the job on our side.

Thank you!

2024-01-11 00:21 UTC, noirbizarre commented
There it is ! Version added markers for 5.4 added on all settings 👍🏼

Thanks for the review and the merge 🙏🏼

2024-01-11 09:29 UTC, Nusnus commented
> There it is ! Version added markers for 5.4 added on all settings 👍🏼
> 
> Thanks for the review and the merge 🙏🏼 

Thank you!!
Unfortunately there's one last detail my friend, the version needs to be first under each title and not after the documentation text.

It's important to keep consistency (see other places) so I hope it's not too annoying to ask for this last fix please @noirbizarre 🙏

2024-01-11 12:10 UTC, auvipy approved these changes
looks good. just the remaining review issues need to be addressed

2024-01-17 23:27 UTC, merged

2024-01-17 23:35 UTC, Nusnus commented
> looks good. just the remaining review issues need to be addressed

Fixed my own comment here: #8802

@noirbizarre all good ❤️

2024-01-17 23:38 UTC, Nusnus commented
😃
```bash
make -C docs changes
open docs/_build/changes/index.html
```
![CleanShot 2024-01-18 at 01 37 34@2x](https://github.com/celery/celery/assets/4662342/473eed4f-7006-4a11-b9d9-f129275d63fd)