Add type annotations to `celery/utils/nodenames.py`
celery/celery pull request #8667
Opened 2023-11-23 23:15 UTC by lyzlisa

## Description

Relates to #7394

2023-11-24 09:35 UTC, Nusnus commented on celery/utils/nodenames.py
> +def node_format(s: str, name: str, **extra: Any) -> str:
```suggestion
def node_format(s: str, name: str, **extra: dict) -> str:
```

2023-11-24 09:36 UTC, Nusnus commented on celery/utils/nodenames.py
> +def host_format(s: str, host: str | None = None, name: str | None = None, **extra: Any) -> str:
```suggestion
def host_format(s: str, host: str | None = None, name: str | None = None, **extra: dict) -> str:
```

2023-11-24 09:41 UTC, Nusnus approved these changes
Fixed a small issue where `Any` was used instead of `dict` for the kwargs `extra`.
Besides looks great!

Good job and thank you for your contribution!

2023-11-24 09:42 UTC, Nusnus commented on celery/utils/nodenames.py
> +    from typing import Any
This can now be removed

2023-11-24 09:45 UTC, Nusnus requested changes
Approved. Pending merge on lint fix @lyzlisa

2023-11-25 04:47 UTC, auvipy requested changes
should we follow this route or consider stub approach?

2023-11-25 06:31 UTC, 50-Course approved these changes
Thank you correcting the annotations. This look great. Thank you for making this MR

2023-11-25 06:39 UTC, 50-Course commented
@auvipy After much consideration, I think instead of annotating the library code directly, would be great enforcing correctness, than using the stubs approach. Looking at `kombu` there's already an ongoing effort using the typing approach as well.

Open to corrections.

2023-11-25 06:41 UTC, auvipy commented
I think we should think about the stub approach to kombu as well

2023-11-25 13:15 UTC, 50-Course commented
I have marked the old review as outdated. Looking to draft patch later for `kombu`, hopefully I start next week. Happy weekend to you.

2023-11-25 13:17 UTC, 50-Course commented
**Update**: I would pass up the first two days of next week as it collides with my birthday, and would spend time with family. See you later.

2023-12-04 20:55 UTC, Nusnus approved these changes
LGTM

2023-12-05 20:58 UTC, merged