app/base.py: Fix DeprecationWarning: datetime.datetime.utcnow()
celery/celery pull request #8726
Opened 2023-12-14 08:41 UTC by cclauss

## Description

### Fix DeprecationWarning: datetime.datetime.utcnow() on Python 3.12
```
lib/python3.12/site-packages/celery/app/base.py:940: DeprecationWarning: datetime.datetime.utcnow()
  is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent
  datetimes in UTC: datetime.datetime.now(datetime.UTC).
    now_in_utc = to_utc(datetime.utcnow())
```
https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow

2023-12-14 10:43 UTC, auvipy requested changes
you can make it draft before the builds are passing

2023-12-14 19:46 UTC, auvipy commented on t/unit/app/test_beat.py
> +        d = x.to_local(datetime.utcnow())  # datetime.utcnow() is deprecated in Python 3.12
shouldn't we change this as well?

2023-12-14 19:47 UTC, cclauss commented on t/unit/app/test_beat.py
> +        d = x.to_local(datetime.utcnow())  # datetime.utcnow() is deprecated in Python 3.12
Tests will fail.

2023-12-18 13:29 UTC, thedrow approved these changes

2023-12-18 15:00 UTC, Nusnus commented
Restarting CI, unrelated error

2023-12-19 19:09 UTC, auvipy approved these changes

2023-12-19 19:10 UTC, merged

2023-12-19 19:10 UTC, auvipy commented
great job! thanks a lot

2023-12-19 20:44 UTC, cclauss commented
There is more `utcnow()` to deal with but these instance are harder to figure out...
* https://github.com/search?q=repo%3Acelery%2Fcelery%20utcnow&type=code