Enable efficient `chord` when using dynamicdb as backend store
celery/celery pull request #8783
Opened 2024-01-10 01:03 UTC by dingxiong

## Description

For `canvas::chord`, only Redis and Memcached currently use an atomic counter to join the parallel tasks. Other backends use a recurring task to poll the completion of the group every second, which is inefficient. 

DynamoDB, on the other hand, supports atomic counter. See [ref](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters).  So in principle, we can use the same technique as Redis backend store to make `chord` more efficient in Dynamodb. This PR adds this support for DynamoDB backend.

2024-01-10 14:02 UTC, Nusnus requested changes
Nice addition!
1. Please add automatic tests.
2. Optionally, also add type hints where it makes sense.

Thank you!

2024-01-10 14:04 UTC, Nusnus requested changes

2024-01-10 14:04 UTC, Nusnus commented on celery/backends/dynamodb.py
> +    def incr(self, key) -> int:
Missing doc

2024-01-10 23:39 UTC, dingxiong commented on celery/backends/dynamodb.py
> +    def incr(self, key) -> int:
@Nusnus added.

2024-01-10 23:42 UTC, dingxiong commented
> Nice addition!
> 
> 1. Please add automatic tests.
> 2. Optionally, also add type hints where it makes sense.
> 
> Thank you!

Thanks for a quick review. I added some unit tests. 
However, I did not find any existing integration test for dynamodb, so I tried to create one for it, but I got stuck on how to replace the backend store only for a few tests. Appreciate your guidance/suggestions.

2024-01-11 16:21 UTC, dingxiong commented
Hi @Nusnus @auvipy Could you help take another look?

2024-01-12 22:30 UTC, dingxiong commented
> Besides the PR looks good; have you done some manual tests maybe with a real environment?
I only tested it with local-dynamodb installation. I will do a test soon with a real AWS account.

2024-01-12 22:42 UTC, Nusnus commented
> > Besides the PR looks good; have you done some manual tests maybe with a real environment?
> 
> @Nusnus  I only tested it with local-dynamodb installation. I will do a test soon with a real AWS account.
> 

That will **very** useful!!
Thank you!

P.S
Feel free to paste logs showing everything works ;)

2024-01-18 23:06 UTC, dingxiong commented
Hi @Nusnus, Below is the testing result with a real AWS account.

code is below
```
@celery_app.task
def add(x: int, y: int, n: int = 30):
    from time import sleep
    print(f"starting sleeping {n}")
    sleep(n)
    print(f"finish sleeping {n}")
    return x + y

@celery_app.task
def tsum(nums):
    """Sum an iterable of numbers."""
    return sum(nums)
````
client side logs are 
```
In [3]: c = chord(header=[add.si(1, 2), add.si(3, 4)], body=tsum.s())
In [4]: result = c()
In [5]: result.get()
Out[5]: 10
```
server side logs are 
```
Task tasks.slack_tasks.add[16b4a1d8-cd59-4dc7-8d42-af38ac66b9c8] received
Task tasks.slack_tasks.add[16b4a1d8-cd59-4dc7-8d42-af38ac66b9c8] about to execute
Task tasks.slack_tasks.add[a02003a8-48f2-486a-8e32-b224076eff6c] received
Task tasks.slack_tasks.add[a02003a8-48f2-486a-8e32-b224076eff6c] about to execute
starting sleeping 30
finish sleeping 30
Task tasks.slack_tasks.tsum[3e6f1527-7ef9-439e-a017-7c95ff3aa65a] requested
starting sleeping 30
finish sleeping 30
Task tasks.slack_tasks.add[16b4a1d8-cd59-4dc7-8d42-af38ac66b9c8] succeeded in 30.192433045012876s: 3
Task tasks.slack_tasks.tsum[3e6f1527-7ef9-439e-a017-7c95ff3aa65a] received
Task tasks.slack_tasks.tsum[3e6f1527-7ef9-439e-a017-7c95ff3aa65a] about to execute
Task tasks.slack_tasks.add[a02003a8-48f2-486a-8e32-b224076eff6c] succeeded in 30.257312100031413s: 7
Task tasks.slack_tasks.tsum[3e6f1527-7ef9-439e-a017-7c95ff3aa65a] succeeded in 0.03086664993315935s: 10
```
Also, this is the screenshot of dyanmodb query result showing that `chord_count = 0` after the chord is initialized.
<img width="699" alt="Screenshot 2024-01-18 at 2 58 19 PM" src="https://github.com/celery/celery/assets/5496402/8829ded1-ef11-414d-8313-b375b8260483">

2024-01-18 23:22 UTC, auvipy reviewed
can you please improve unit test coverage for this backend?

2024-01-19 07:19 UTC, dingxiong commented
> can you please improve unit test coverage for this backend?

@auvipy Yes sure. I added one more unit test and codecov score looks good now. But one test matrix `Smoke-stamping 3.11` failed. I doubt it is related to my change. Could you help retrigger the CI?

2024-01-25 09:10 UTC, dingxiong commented
Hi, @auvipy @Nusnus, any more concerns?

2024-01-29 12:59 UTC, auvipy approved these changes

2024-01-29 13:00 UTC, merged

2024-01-29 13:01 UTC, auvipy commented
it was all green! welcome aboard!