Add support for Pydantic model validation/serialization (fixes #8751)
celery/celery pull request #9023
Opened 2024-05-14 10:08 UTC by mathiasertl

Allow validation of arguments using Pydantic, as well as result serialization.

With this PR, you can pass `pydantic=True` to a task decorator. If set, any argument type hinted as a Pydantic model will be validated (note: this means data validation *and* loading into the model class Pydantic speak) to that model, and any result matching a return type annotation will automatically be converted to a dict (using `model_dump()`.

With this feature, tasks look a lot more like FastAPI endpoints, where query arguments, request and response bodies are validated/serialized using Pydantic. The advantage is of course automatic data validation and safer typing. mypy will catch type hinting errors, and IDEs auto-complete values in the models.

2024-05-14 11:00 UTC, mathiasertl commented
Note: I force-pushed a few minor changes to make sure that test coverage does not decrease.

2024-07-26 11:27 UTC, Arthur-CWW approved these changes

2024-07-26 11:28 UTC, Arthur-CWW approved these changes

2024-07-28 06:04 UTC, auvipy requested changes
Although I'm not 100% about the API design here, but I think the feature implementation looks good. if we can / should add some sort of integration test it would easier to decide to include in v5.5.0 release.

2024-07-28 11:35 UTC, thedrow requested changes
I agree that an integration test is required to merge this PR.
It should be simple enough to implement. If you need help, let me know.

2024-07-28 12:04 UTC, mathiasertl commented
> Although I'm not 100% about the API design here,

Obviously a very subjective matter. You're the owner of the project, just let me know if you desire any changes!

2024-07-28 12:50 UTC, mathiasertl commented
I just rebased the branch, added another test as well as a simple integration test. I hope it is sufficient.

Would love to see this in Celery 5.5!

2024-07-29 12:15 UTC, thedrow approved these changes

2024-07-29 12:39 UTC, mathiasertl commented
Oh I completely missed that, I'm sorry. 

Considering Python 3.8 is EOL by this October, is the project still aiming to support it for the upcoming release? Your decision of course, just so I don't make any unnecessary effort.

The test seems to fail due to some intricacy mocking import_module. Since it's otherwise straight forward, can I just exclude that test for 3.8?

2024-07-29 20:48 UTC, Nusnus commented
> Oh I completely missed that, I'm sorry.
> 
> Considering Python 3.8 is EOL by this October, is the project still aiming to support it for the upcoming release? Your decision of course, just so I don't make any unnecessary effort.
> 
> The test seems to fail due to some intricacy mocking import_module. Since it's otherwise straight forward, can I just exclude that test for 3.8?

The next release (v5.5.0) will be before October, so we will still support Python 3.8.
That being said, it seems the unit & integration tests are passing with Python 3.8 so I guess you’ve fixed the Py38 specific issue already?
Although now all of the smoke tests are failing..

2024-07-30 04:05 UTC, auvipy requested changes
let's fix the smoke tests before we move forward?

2024-07-30 05:30 UTC, mathiasertl commented
Yes, Python 3.8 is fixed.

I'm at a loss about these smoke tests. They all just time out, no output otherwise. The last change I made (for py 3.8 compat) was really just splitting the `with` statement in that unit test into two lines.

Is it possible to retrigger those tests? Perhaps they're unstable or external factors caused the time out?

2024-07-30 19:59 UTC, Nusnus commented
This is why the smoke tests are failing.
This is the Dockerfile of the container it fails to run: https://github.com/celery/celery/blob/main/t/smoke/workers/docker/dev
```console
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app':
Unable to load celery application.
While trying to load the module app the following error occurred:
Traceback (most recent call last):
  File "/celery/celery/bin/celery.py", line 58, in convert
    return find_app(value)
           ^^^^^^^^^^^^^^^
  File "/celery/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/celery/celery/utils/imports.py", line 109, in import_from_cwd
    return imp(module, package=package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/app.py", line 13, in <module>
    from t.integration.tasks import *
  File "/app/t/integration/tasks.py", line 5, in <module>
    from pydantic import BaseModel
ModuleNotFoundError: No module named 'pydantic'

===================================================================================== short test summary info =====================================================================================
ERROR t/smoke/tests/failover/test_broker_failover.py::test_broker_failover::test_killing_first_broker[celery_setup_worker-celery_redis_backend] - pytest_docker_tools.exceptions.ContainerNotReady: Timeout while waiting for container to be ready
```

2024-08-01 19:19 UTC, mathiasertl commented
I fixed that issue. That fixes some checks, but some still remain. Again, they have zero output indicating what the error is (the lines you quoted above also did not occur in logs). Can you please further assist and also tell me how to find those logs?

2024-08-02 16:56 UTC, Nusnus commented
@mathiasertl
> Again, they have zero output indicating what the error is (the lines you quoted above also did not occur in logs). Can you please further assist and also tell me how to find those logs?

You can run the smoke tests locally (req: Docker installed) with `tox -e 3.12-smoke -- -k stamping --reruns 0`
The CI uses `pytest-xdist` and runs `tox -e 3.12-smoke -- -n auto`.

This will show the reason it fails:
```console
tox -e 3.12-smoke -- -k stamping --reruns 0
ROOT: will run in automatically provisioned tox, host /opt/homebrew/Cellar/tox/4.16.0/libexec/bin/python is missing [requires (has)]: tox-gh-actions
ROOT: provision> .tox/.tox/bin/python -m tox -e 3.12-smoke -- -k stamping --reruns 0
ROOT: tox-gh-actions won't override envlist because tox is not running in GitHub Actions
.pkg: _optional_hooks> python /Users/nusnus/dev/GitHub/celery/.tox/.tox/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: get_requires_for_build_editable> python /Users/nusnus/dev/GitHub/celery/.tox/.tox/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
.pkg: build_editable> python /Users/nusnus/dev/GitHub/celery/.tox/.tox/lib/python3.12/site-packages/pyproject_api/_backend.py True setuptools.build_meta __legacy__
3.12-smoke: install_package> python -I -m pip install --force-reinstall --no-deps /Users/nusnus/dev/GitHub/celery/.tox/.tmp/package/10/celery-5.5.0b1-0.editable-py3-none-any.whl
3.12-smoke: commands[0]> pytest -xsvv t/smoke --dist=loadscope --reruns 10 --reruns-delay 60 --rerun-except AssertionError -k stamping --reruns 0
======================================================================================= test session starts =======================================================================================
platform darwin -- Python 3.12.4, pytest-8.3.2, pluggy-1.5.0 -- /Users/nusnus/dev/GitHub/celery/.tox/3.12-smoke/bin/python
cachedir: .tox/3.12-smoke/.pytest_cache
rootdir: /Users/nusnus/dev/GitHub/celery
configfile: pyproject.toml
plugins: docker-tools-3.1.3, cov-5.0.0, github-actions-annotate-failures-0.2.0, click-1.1.0, celery-1.0.1, rerunfailures-14.0, order-1.2.1, anyio-4.4.0, subtests-0.13.1, timeout-2.3.1, xdist-3.6.1
collected 146 items / 100 deselected / 46 selected

t/smoke/tests/stamping/test_hybrid_cluster.py::test_stamping_hybrid_worker_cluster::test_sanity[celery_worker_cluster0-celery_redis_broker-celery_redis_backend] Fetching redis:latest
Creating network pytest-8a04c883-cab5-4394-9534-c1a6c2f3563d
Waiting for container to be ready.RedisContainer::sad_payne is ready.

Waiting for container to be ready.RedisContainer::crazy_payne is ready.

Waiting for container to be ready.RedisContainer::thirsty_goldwasser is ready.

Creating volume pytest-44f98127-d9ad-41e5-8b0f-c06d7ce48144
Building ............................................................................
Waiting for container to be ready.Waiting for SmokeWorkerContainer::romantic_poitras to get ready...
SmokeWorkerContainer::romantic_poitras is ready.

PASSED
t/smoke/tests/stamping/test_hybrid_cluster.py::test_stamping_hybrid_worker_cluster::test_sanity[celery_worker_cluster0-celery_rabbitmq_broker-celery_redis_backend] Creating network pytest-de09d334-5a34-4018-963f-58c36a9ece87
Waiting for container to be ready.RedisContainer::sad_buck is ready.

Waiting for container to be ready.Waiting for RabbitMQContainer::dazzling_jennings to get ready.......
RabbitMQContainer::dazzling_jennings is ready.

Waiting for container to be ready.RedisContainer::angry_noyce is ready.

Creating volume pytest-a0e380a1-860f-4878-86d3-dbea9df51499
Waiting for container to be ready.Waiting for SmokeWorkerContainer::naughty_chandrasekhar to get ready...
SmokeWorkerContainer::naughty_chandrasekhar is ready.

PASSED
t/smoke/tests/stamping/test_hybrid_cluster.py::test_stamping_hybrid_worker_cluster::test_sanity[celery_worker_cluster1-celery_redis_broker-celery_redis_backend] Creating network pytest-c9c43f85-39fb-476c-8437-a181de6924f6
Waiting for container to be ready.RedisContainer::zen_booth is ready.

Waiting for container to be ready.RedisContainer::nice_cori is ready.

Waiting for container to be ready.RedisContainer::epic_gould is ready.

Creating volume pytest-2cb2416b-7546-4801-9d37-2c7a351a6ec3
Building ...........................................................................
Waiting for container to be ready.Waiting for LegacyWorkerContainer::wonderful_poincare to get ready..............................
Waiting for LegacyWorkerContainer::wonderful_poincare to get ready..............................
Waiting for LegacyWorkerContainer::wonderful_poincare to get ready..............................

ERROR

============================================================================================= ERRORS ==============================================================================================
_______________________________ ERROR at setup of test_stamping_hybrid_worker_cluster.test_sanity[celery_worker_cluster1-celery_redis_broker-celery_redis_backend] ________________________________

request = <SubRequest 'celery_legacy_worker_container' for <Function test_sanity[celery_worker_cluster1-celery_redis_broker-celery_redis_backend]>>
docker_client = <docker.client.DockerClient object at 0x104a2e600>, wrapper_class = <class 't.smoke.tests.stamping.workers.legacy.LegacyWorkerContainer'>
kwargs = {'detach': True, 'environment': {'CELERY_BROKER_URL': 'redis://441b7f14e235/0', 'CELERY_RESULT_BACKEND': 'redis://5278...e': 'False', 'pytest-docker-tools.signature': 'd1e973f48d660c13196a96312ebf47dfdc311bef3c24d7cacf926078cfec7b7b'}, ...}
signature = 'd1e973f48d660c13196a96312ebf47dfdc311bef3c24d7cacf926078cfec7b7b', timeout = 60, container = <t.smoke.tests.stamping.workers.legacy.LegacyWorkerContainer object at 0x104ce1ee0>

    @fixture_factory()
    def container(request, docker_client, wrapper_class, **kwargs):
        """ Docker container: image={image} """

        wrapper_class = wrapper_class or Container

        kwargs.update({"detach": True})
        set_reusable_labels(kwargs, request)

        signature = hash_params(kwargs)
        set_signature(kwargs, signature)

        if request.config.option.reuse_containers:
            if "name" not in kwargs.keys():
                pytest.fail(
                    "Tried to use '--reuse-containers' command line argument without "
                    "setting 'name' attribute on container"
                )

            name = kwargs["name"]

            try:
                current = docker_client.containers.get(name)
            except NotFound:
                pass
            else:
                # Found a container with the right name, but it doesn't have pytest-docker-tools labels
                # We shouldn't just clobber it, its not ours. Bail out.
                if not is_reusable_container(current):
                    pytest.fail(
                        f"Tried to reuse {name} but it does not appear to be a reusable container"
                    )

                # It's ours, and its not stale. Reuse it!
                if check_signature(current.labels, signature):
                    return wrapper_class(current)

                # It's ours and it is stale. Clobber it.
                print(f"Removing stale reusable container: {name}")
                current.remove(force=True)

        timeout = kwargs.pop("timeout", 30)

        raw_container = docker_client.containers.run(**kwargs)
        if not request.config.option.reuse_containers:
            request.addfinalizer(
                lambda: raw_container.remove(force=True) and raw_container.wait(timeout=10)
            )

        container = wrapper_class(raw_container)

        try:
>           wait_for_callable("Waiting for container to be ready", container.ready, timeout)

.tox/3.12-smoke/lib/python3.12/site-packages/pytest_docker_tools/factories/container.py:69:
_ _ _ _ _ _ _  [...]

2024-08-03 10:28 UTC, auvipy approved these changes

2024-08-03 11:36 UTC, mathiasertl commented
@Nusnus Thanks for the support and also for the fix!

2024-08-03 13:44 UTC, Nusnus approved these changes
@mathiasertl 
> @Nusnus Thanks for the support and also for the fix!

Glad to help! This is a very cool and important contribution, and I apologize for the delay in prioritizing it.

I’ve finally reviewed and LGTM + nice coverage on the feature!
My only comment is probably that I’d add the `CONTRIBUTING.rst` and `docker/docker-compose.yml` to its own PR but it’s totally optional in our case :)

Approved by the entire team it seems, so we can merge.
Just wanted to ask before, would you like to maybe also add a new official example? Something basic that can fit the [celery/examples](https://github.com/celery/celery/tree/main/examples) to show a quick demo, to add the cherry on 🍒

2024-08-03 14:39 UTC, mathiasertl commented
> My only comment is probably that I’d add the CONTRIBUTING.rst and docker/docker-compose.yml to its own PR but it’s totally optional in our case :)

Done with #9171

2024-08-03 14:54 UTC, Nusnus approved these changes
@mathiasertl 
> > My only comment is probably that I’d add the CONTRIBUTING.rst and docker/docker-compose.yml to its own PR but it’s totally optional in our case :)
> 
> Done with #9171
> 
> > Just wanted to ask before, would you like to maybe also add a new official example? Something basic that can fit the [celery/examples](https://github.com/celery/celery/tree/main/examples) to show a quick demo, to add the cherry on 🍒
> 
> Done!

🔥🔥🔥

#9171 -> Merged.

This one will be merged as soon as the CI finishes!!

Thank you very much!
Great new addition for the new release!

Nice Job 👏

2024-08-03 15:50 UTC, merged

2024-09-10 04:28 UTC, Robin528919 commented
[2024-09-10 12:21:28,938: ERROR/MainProcess] Task tw_login_start[274b74c3-8aab-4cb8-a85a-4762f2216126] raised unexpected: EncodeError(TypeError('Object of type LoginTask is not JSON serializable'))
Traceback (most recent call last):
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type LoginTask is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery_aio_pool/tracer.py", line 304, in trace_task
    task.backend.mark_as_done(
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery/backends/base.py", line 157, in mark_as_done
    self.store_result(task_id, result, state, request=request)
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery/backends/base.py", line 526, in store_result
    self._store_result(task_id, result, state, traceback,
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery/backends/base.py", line 981, in _store_result
    self._set_with_state(self.get_key_for_task(task_id), self.encode(meta), state)
                                                         ^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery/backends/base.py", line 413, in encode
    _, _, payload = self._encode(data)
                    ^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/celery/backends/base.py", line 417, in _encode
    return dumps(data, serializer=self.serializer)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 219, in dumps
    with _reraise_errors(EncodeError):
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/contextlib.py", line 158, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 45, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/exceptions.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 41, in _reraise_errors
    yield
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/serialization.py", line 220, in dumps
    payload = encoder(data)
              ^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/utils/json.py", line 63, in dumps
    return _dumps(s, cls=cls, **dict(default_kwargs, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/site-packages/kombu/utils/json.py", line 47, in default
    return super().default(o)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/zhangpengqiang/opt/anaconda3/envs/Twitter/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type LoginTask is not JSON serializable




Enabling pydantic=true causes json errors, what should I do?

2024-09-14 08:08 UTC, Robin528919 commented
Wants pydantic_strict as a configuration item

2024-09-14 11:55 UTC, auvipy commented
care to share code example of use case please?

2024-09-15 14:34 UTC, mathiasertl commented
I think the request is valid. However, I'm afk for another two weeks and cannot currently work on it.

Kr, Mat

2024-09-22 12:14 UTC, anderser commented
First: This is a great addition to Celery, thanks! 

I have a task that returns a list of Pydantic models like `List[MyItem]`. I use SQL Alchemy result backend (but I suppose this is relevant to other backends aswell). Using a list of Pydantic models, the result is not serialized to json, and I suppose that is due to have the serializer works (looking for BaseModel). Should this be supported (i.e. a List of Pydantic models), or do I have to use a "wrapper" model like this: 

```
class TaskResponse(BaseModel):
    items: List[MyItem]
```

and use that for the task response?

2024-09-22 21:24 UTC, mathiasertl commented
Hi! 

Can you show the task code as well?

Kr, Mat

2024-09-25 20:04 UTC, mathiasertl commented
Hi @anderser!

You are correct in that Pydantic models as part of a generic container (such as `List[]`) are not handled by the current implementation.

> would be practical (at least in my case) to be able to return a List of models in a task. But I don't know if that is out of scope for this Pydantic implementation. A solution could be to check if the response is a list of models, but then again, where should you stop checking/nesting? I am not sure :)

Implementing it is probably technically possible, but then why not handle e.g. something like `list[tuple[MyModel, MyModel]]` etc. Where does it stop. A full recursive implementation on this seems pretty extensive. I'm open to reviewing such a MR, but not sure I would want to implement it.

However, if only the data structure is important to you, you could also use a [root model](https://docs.pydantic.dev/latest/concepts/models/#rootmodel-and-custom-root-types) to get the same response structure. Like this (note: haven't tested it):

```python
class MyItem(BaseModel):
    name: str
    age: int

TaskResponse = RootModel(List[MyItem])

def mytask() -> TaskResponse:
    ...
```

would this work for you?

2024-09-25 20:06 UTC, mathiasertl commented
There is one thing that probably (haven't checked - maybe I implemented and forgot about it? :-)) also doesn't work and really should be implemented: optional parameters. So something like this:

```python
def mytask(param: Optional[MyModel] = None) -> None:
    return
```

... will probably not convert to MyModel if it is passed. I will make a separate PR on this.

kr, Mat

2024-09-25 20:08 UTC, Nusnus commented
> There is one thing that probably (haven't checked - maybe I implemented and forgot about it? :-)) also doesn't work and really should be implemented: optional parameters. So something like this:
> 
> ```python
> def mytask(param: Optional[MyModel] = None) -> None:
>     return
> ```
> 
> ... will probably not convert to MyModel if it is passed. I will make a separate PR on this.
> 
> kr, Mat

Awesome - please tag me for review!

Thanks

2024-09-26 07:15 UTC, anderser commented
Hi. Ref this:

> TaskResponse = RootModel(List[MyItem])
> 
> def mytask() -> TaskResponse:
>     ...
> ```
> 
> would this work for you?

Yes, I already implemented that, sorry forgot to mention that in the comment previously. It works and is probably a more pydantic way than trying to find models deep down in a list/tuple structure. So I think I will rest my case here :)

And nice to see that Optional will be handled. 

Another thing that would be nice would be to be able to set pydantic=True and pydantic_strict=True on a Task class (I use custom Task classes) or in the settings, so we don't have to set those kwargs on every task function. 

Keep up the good work!

Anders

2024-09-27 22:38 UTC, mathiasertl commented
> And nice to see that Optional will be handled.

Addressed in #9319.

> Another thing that would be nice would be to be able to set pydantic=True and pydantic_strict=True on a Task class (I use custom Task classes) or in the settings, so we don't have to set those kwargs on every task function.

All for it, but I couldn't quite figure out how to do that. If somebody provides hints, I could implement this. Better yet... someone else can do it too, of course :-).

2024-12-20 08:39 UTC, MarcelloCuoghi commented
Hi, thanks you for this feature, it's really awesome and I'm already using it in my project.
One little thing I miss from the example is that when you call a task execution you need to dump the model in json, is that right?
Because in the first steps using this I got exception about serializations and did not understand why. Maybe I missed it myself, so I'm sorry if this is already covered. If it is like this, my suggestion is to add in the example also the calling of the task with the code
 ```python
x.delay(arg.model_dump(mode="json"))
```
Or something like that.

2024-12-20 09:55 UTC, mathiasertl commented
Hi @MarcelloCuoghi !

Great to hear that this feature works well for you.

Yes, you're right. At the moment, this covers only the task side. There is a big note in the chapter documenting this.

However, you're not the first being confused by this limitation, I'm open to suggestions how to improve documentation.

I think it's also possible to implement automatic serialization. But I don't currently have time to work on it.

Kr, Mat

2024-12-20 10:50 UTC, MarcelloCuoghi commented
Oh you're right, I was searching in wrong documentation and did not find anything, I saw only in the example folder in the project. Yes It's clearer now thank you very much

2025-02-01 11:33 UTC, tomas-polach commented
> ```python
> x.delay(arg.model_dump(mode="json"))
> ```

thank you so much! this was the missing puzzle-piece to overcome the error:
```
kombu.exceptions.EncodeError: Object of type ArgPydanticModel is not JSON serializable
```

+1 for automatic serialization

2025-02-02 05:12 UTC, auvipy commented
> > ```python
> > x.delay(arg.model_dump(mode="json"))
> > ```
> 
> thank you so much! this and using version 5.5 were the two missing puzzle-piece to overcome the error:
> 
> ```
> kombu.exceptions.EncodeError: Object of type ArgPydanticModel is not JSON serializable
> ```
> 
> +1 for automatic serialization

just to make sure, this is working right?

2025-02-02 08:28 UTC, mathiasertl commented
I haven't seen any case where it didn't work.