Fix missing import 9098
celery/celery pull request #9099
Opened 2024-06-26 03:12 UTC by giovanni1106

**Fixes #9098**

## Description

The code snippet provided in the documentation needs an additional import to function correctly. Without this import, the code does not raise any errors, but it fails to discover `@shared_task`s in other files. This PR adds the necessary import statement.

**Link to Documentation:** [First steps with Django](https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html)

2024-06-26 15:25 UTC, thedrow approved these changes

2024-06-26 15:26 UTC, thedrow commented
Can you please fix the linter error?

2024-06-28 17:07 UTC, giovanni1106 commented
> Can you please fix the linter error?

This error occurs because Celery references this import as a string, so the linter does not recognize its usage.

---

_Image 1: lint error ([link](https://github.com/celery/celery/actions/runs/9672965372/job/26697737921?pr=9099))_.

![image](https://github.com/celery/celery/assets/63993401/7549cae0-5631-4989-8981-40e56ed002b6)

---

_Image 2: Import in code ([link](https://github.com/giovanni1106/celery/blob/fix-missing-import-9098/examples/django/proj/celery.py))_.

![image](https://github.com/celery/celery/assets/63993401/3b306382-f8cd-4942-9688-117d459ff12d)

2024-06-30 22:22 UTC, Nusnus requested changes
Please rename the PR to match the changes it introduces

2024-06-30 22:27 UTC, Nusnus commented
> > Can you please fix the linter error?
> 
> This error occurs because Celery references this import as a string, so the linter does not recognize its usage.
> 
> _Image 1: lint error ([link](https://github.com/celery/celery/actions/runs/9672965372/job/26697737921?pr=9099))_.
> 
> ![image](https://private-user-images.githubusercontent.com/63993401/344252376-7549cae0-5631-4989-8981-40e56ed002b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTIzNzYtNzU0OWNhZTAtNTYzMS00OTg5LTg5ODEtNDBlNTZlZDAwMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTQ0NTdlNTlmZDBkZjRkZGE2OTU0NzBlMzM5NzgzMmU1YzAyMjAzOTIyMjIxMGMyMDIwZTA3NzE4YzIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuvSxjgepMNksWBq8tA5GRaZkTpWUKfSP7FVw6ikQYQ)
> 
> _Image 2: Import in code ([link](https://github.com/giovanni1106/celery/blob/fix-missing-import-9098/examples/django/proj/celery.py))_.
> 
> ![image](https://private-user-images.githubusercontent.com/63993401/344253940-3b306382-f8cd-4942-9688-117d459ff12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTM5NDAtM2IzMDYzODItZjhjZC00OTQyLTk2ODgtMTE3ZDQ1OWZmMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjFmODhmZjY2MTQ4NmY3ZmY4ZDU3YmQzM2NhMDM1ZWZhOGNmMjhiMGNhYTYyMjk1NjkzNzk0ZDliMzY4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-HEFeo2ZFacaA2Fn6TFDbcRQEhzsEloMQXTl_kdrpw)

I don’t “love” this, but you can do `f'django.conf:{settings.__name__}’`.
If you think it’s really ugly, I’m positive we can also live with a `# noqa` to skip the linting. After all this is just an example project.

2024-06-30 22:30 UTC, Nusnus commented
Also, don’t worry if the smoke tests are failing.
They are flaky due to the instability of Redis. This will be fixed in the next release.

For now I’ll be watching the CI and if the smoke tests will fail I’ll rerun them.
This PR only changes the examples so there’s no reason to worry.

2024-07-01 17:58 UTC, giovanni1106 commented
> Please rename the PR to match the changes it introduces

Adjusted

2024-07-01 18:03 UTC, giovanni1106 commented
> > > Can you please fix the linter error?
> > 
> > 
> > This error occurs because Celery references this import as a string, so the linter does not recognize its usage.
> > _Image 1: lint error ([link](https://github.com/celery/celery/actions/runs/9672965372/job/26697737921?pr=9099))_.
> > ![image](https://private-user-images.githubusercontent.com/63993401/344252376-7549cae0-5631-4989-8981-40e56ed002b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTIzNzYtNzU0OWNhZTAtNTYzMS00OTg5LTg5ODEtNDBlNTZlZDAwMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTQ0NTdlNTlmZDBkZjRkZGE2OTU0NzBlMzM5NzgzMmU1YzAyMjAzOTIyMjIxMGMyMDIwZTA3NzE4YzIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuvSxjgepMNksWBq8tA5GRaZkTpWUKfSP7FVw6ikQYQ)
> > _Image 2: Import in code ([link](https://github.com/giovanni1106/celery/blob/fix-missing-import-9098/examples/django/proj/celery.py))_.
> > ![image](https://private-user-images.githubusercontent.com/63993401/344253940-3b306382-f8cd-4942-9688-117d459ff12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTM5NDAtM2IzMDYzODItZjhjZC00OTQyLTk2ODgtMTE3ZDQ1OWZmMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjFmODhmZjY2MTQ4NmY3ZmY4ZDU3YmQzM2NhMDM1ZWZhOGNmMjhiMGNhYTYyMjk1NjkzNzk0ZDliMzY4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-HEFeo2ZFacaA2Fn6TFDbcRQEhzsEloMQXTl_kdrpw)
> 
> I don’t “love” this, but you can do `f'django.conf:{settings.__name__}'`. If you think it’s really ugly, I’m positive we can also live with a `# noqa` to skip the linting. After all this is just an example project.

Thanks for the clarification. Do you want me to implement the change using f'django.conf:{settings.__name__}', or should we leave it as is and use # noqa to skip the linting? Please let me know your preference.

2024-07-01 22:27 UTC, Nusnus commented
> > > > Can you please fix the linter error?
> > > 
> > > 
> > > This error occurs because Celery references this import as a string, so the linter does not recognize its usage.
> > > _Image 1: lint error ([link](https://github.com/celery/celery/actions/runs/9672965372/job/26697737921?pr=9099))_.
> > > ![image](https://private-user-images.githubusercontent.com/63993401/344252376-7549cae0-5631-4989-8981-40e56ed002b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTIzNzYtNzU0OWNhZTAtNTYzMS00OTg5LTg5ODEtNDBlNTZlZDAwMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTQ0NTdlNTlmZDBkZjRkZGE2OTU0NzBlMzM5NzgzMmU1YzAyMjAzOTIyMjIxMGMyMDIwZTA3NzE4YzIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuvSxjgepMNksWBq8tA5GRaZkTpWUKfSP7FVw6ikQYQ)
> > > _Image 2: Import in code ([link](https://github.com/giovanni1106/celery/blob/fix-missing-import-9098/examples/django/proj/celery.py))_.
> > > ![image](https://private-user-images.githubusercontent.com/63993401/344253940-3b306382-f8cd-4942-9688-117d459ff12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTM5NDAtM2IzMDYzODItZjhjZC00OTQyLTk2ODgtMTE3ZDQ1OWZmMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjFmODhmZjY2MTQ4NmY3ZmY4ZDU3YmQzM2NhMDM1ZWZhOGNmMjhiMGNhYTYyMjk1NjkzNzk0ZDliMzY4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-HEFeo2ZFacaA2Fn6TFDbcRQEhzsEloMQXTl_kdrpw)
> > 
> > 
> > I don’t “love” this, but you can do `f'django.conf:{settings.__name__}'`. If you think it’s really ugly, I’m positive we can also live with a `# noqa` to skip the linting. After all this is just an example project.
> 
> Thanks for the clarification. Do you want me to implement the change using `f'django.conf:{settings.__name__}'`, or should we leave it as is and use `# noqa` to skip the linting? Please let me know your preference.

Use the f-string then @giovanni1106 

Thanks!

2024-07-02 16:18 UTC, giovanni1106 commented
> > > > > Can you please fix the linter error?
> > > > 
> > > > 
> > > > This error occurs because Celery references this import as a string, so the linter does not recognize its usage.
> > > > _Image 1: lint error ([link](https://github.com/celery/celery/actions/runs/9672965372/job/26697737921?pr=9099))_.
> > > > ![image](https://private-user-images.githubusercontent.com/63993401/344252376-7549cae0-5631-4989-8981-40e56ed002b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTIzNzYtNzU0OWNhZTAtNTYzMS00OTg5LTg5ODEtNDBlNTZlZDAwMmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwMTQ0NTdlNTlmZDBkZjRkZGE2OTU0NzBlMzM5NzgzMmU1YzAyMjAzOTIyMjIxMGMyMDIwZTA3NzE4YzIwYjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SuvSxjgepMNksWBq8tA5GRaZkTpWUKfSP7FVw6ikQYQ)
> > > > _Image 2: Import in code ([link](https://github.com/giovanni1106/celery/blob/fix-missing-import-9098/examples/django/proj/celery.py))_.
> > > > ![image](https://private-user-images.githubusercontent.com/63993401/344253940-3b306382-f8cd-4942-9688-117d459ff12d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3ODY1MjUsIm5iZiI6MTcxOTc4NjIyNSwicGF0aCI6Ii82Mzk5MzQwMS8zNDQyNTM5NDAtM2IzMDYzODItZjhjZC00OTQyLTk2ODgtMTE3ZDQ1OWZmMTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDIyMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4MjFmODhmZjY2MTQ4NmY3ZmY4ZDU3YmQzM2NhMDM1ZWZhOGNmMjhiMGNhYTYyMjk1NjkzNzk0ZDliMzY4M2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y-HEFeo2ZFacaA2Fn6TFDbcRQEhzsEloMQXTl_kdrpw)
> > > 
> > > 
> > > I don’t “love” this, but you can do `f'django.conf:{settings.__name__}'`. If you think it’s really ugly, I’m positive we can also live with a `# noqa` to skip the linting. After all this is just an example project.
> > 
> > 
> > Thanks for the clarification. Do you want me to implement the change using `f'django.conf:{settings.__name__}'`, or should we leave it as is and use `# noqa` to skip the linting? Please let me know your preference.
> 
> Use the f-string then @giovanni1106
> 
> Thanks!

Done!

2024-07-03 10:49 UTC, Nusnus approved these changes

2024-07-03 10:49 UTC, merged