Add basic helm chart for celery
celery/celery pull request #9181
Opened 2024-08-12 07:51 UTC by necromancerthedark

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

2024-08-12 10:25 UTC, thedrow commented
The linter yaml in precommit is failing. Please check the output and fix the issues it points out to.

2024-08-12 15:33 UTC, auvipy requested changes

2024-08-12 15:33 UTC, auvipy commented on helm-chart/templates/secret.yaml
> +{{- end }}
```suggestion
{{- end }}

```

2024-08-12 15:33 UTC, auvipy commented on helm-chart/templates/deployment.yaml
> +      {{- end }}
```suggestion
      {{- end }}
      
```

2024-08-12 15:33 UTC, auvipy commented on helm-chart/templates/configmap.yaml
> +{{- .Values.configmap.data | toYaml | nindent 2 }}
```suggestion
{{- .Values.configmap.data | toYaml | nindent 2 }}

```

2024-08-12 18:25 UTC, necromancerthedark commented
@thedrow added exclusion for helm chart in check-yaml, 
took reference from this pre-commit issue: https://github.com/pre-commit/pre-commit-hooks/issues/420

2024-08-13 05:28 UTC, auvipy requested changes
can we add basic introductory documentation for how to use this chart for both local / deployment? including appropriate links for better understanding for people willing to try it?

2024-08-13 05:31 UTC, necromancerthedark commented
sure,
one question: should Readme for this go inside helm chart repo or somewhere outside.
My opinion would be inside the helm-chart folder only

2024-08-13 05:43 UTC, auvipy commented
lets start with readme inside this repo first.... in future we will determine should this be recommended in deployment docs in celery

2024-08-20 08:07 UTC, merged