print is not thread-safe, so should not be used in signal handler
celery/celery pull request #9222
Opened 2024-09-01 02:15 UTC by Zhong-z

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

I sometime got  `RuntimeError: reentrant call inside <_io.BufferedWriter name='<stdout>'>` during worker's lifecycle. 

see others have similar issue https://stackoverflow.com/questions/45680378/how-to-explain-the-reentrant-runtimeerror-caused-by-printing-in-signal-handlers#comment126485747_56330763

We should not use `print` inside signal handlers because it's not thread-safe (not actually safe as the name suggested). There might be other cases of `print` inside signal handlers, but I was only able to identify these obvious ones. 😄 

See similar issue and thread in [gunicorn](https://github.com/benoitc/gunicorn/pull/3064#issuecomment-1788134170).

An alternative solution is not to log/print anything.

2024-09-04 06:51 UTC, auvipy requested changes
please fix the merge conflicts

2024-09-04 10:07 UTC, Nusnus approved these changes

2024-09-04 16:25 UTC, Nusnus requested changes
@Zhong-z the smoke tests are failing on a real issue.
```console
2024-09-04T12:47:28.6884582Z ------------------- default_worker_container: silly_villani --------------------
2024-09-04T12:47:28.6885146Z Changed worker configuration: {
2024-09-04T12:47:28.6885584Z     "worker_pool_restarts": true,
2024-09-04T12:47:28.6885984Z     "task_acks_late": true
2024-09-04T12:47:28.6886344Z }
2024-09-04T12:47:28.6886680Z  
2024-09-04T12:47:28.6887193Z  -------------- smoke_tests_worker@be6028dd6fb3 v5.5.0b2 (immunity)
2024-09-04T12:47:28.6887678Z --- ***** ----- 
2024-09-04T12:47:28.6888279Z -- ******* ---- Linux-6.5.0-1025-azure-x86_64-with-glibc2.36 2024-09-04 12:46:12
2024-09-04T12:47:28.6888823Z - *** --- * --- 
2024-09-04T12:47:28.6889251Z - ** ---------- [config]
2024-09-04T12:47:28.6889732Z - ** ---------- .> app:         celery_test_app:0x7f050969dcd0
2024-09-04T12:47:28.6890303Z - ** ---------- .> transport:   sqs://b09f0037a174:4566//
2024-09-04T12:47:28.6890970Z - ** ---------- .> results:     redis://161584cfa3c5/0
2024-09-04T12:47:28.6891510Z - *** --- * --- .> concurrency: 4 (prefork)
2024-09-04T12:47:28.6892274Z -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
2024-09-04T12:47:28.6892899Z --- ***** ----- 
2024-09-04T12:47:28.6893222Z  -------------- [queues]
2024-09-04T12:47:28.6893852Z                 .> smoke_tests_queue exchange=smoke_tests_queue(direct) key=smoke_tests_queue
2024-09-04T12:47:28.6894479Z                 
2024-09-04T12:47:28.6894649Z 
2024-09-04T12:47:28.6894810Z [tasks]
2024-09-04T12:47:28.6895158Z   . pytest_celery.vendors.worker.tasks.add
2024-09-04T12:47:28.6895716Z   . pytest_celery.vendors.worker.tasks.add_replaced
2024-09-04T12:47:28.6896243Z   . pytest_celery.vendors.worker.tasks.fail
2024-09-04T12:47:28.6896741Z   . pytest_celery.vendors.worker.tasks.identity
2024-09-04T12:47:28.6897300Z   . pytest_celery.vendors.worker.tasks.noop
2024-09-04T12:47:28.6897797Z   . pytest_celery.vendors.worker.tasks.ping
2024-09-04T12:47:28.6898242Z   . pytest_celery.vendors.worker.tasks.sleep
2024-09-04T12:47:28.6898802Z   . pytest_celery.vendors.worker.tasks.xsum
2024-09-04T12:47:28.6899323Z   . t.integration.tasks.add
2024-09-04T12:47:28.6899790Z   . t.integration.tasks.add_chord_to_chord
2024-09-04T12:47:28.6900275Z   . t.integration.tasks.add_ignore_result
2024-09-04T12:47:28.6900686Z   . t.integration.tasks.add_not_typed
2024-09-04T12:47:28.6901176Z   . t.integration.tasks.add_pydantic
2024-09-04T12:47:28.6901620Z   . t.integration.tasks.add_replaced
2024-09-04T12:47:28.6902046Z   . t.integration.tasks.add_to_all
2024-09-04T12:47:28.6902558Z   . t.integration.tasks.add_to_all_to_chord
2024-09-04T12:47:28.6903143Z   . t.integration.tasks.build_chain_inside_task
2024-09-04T12:47:28.6903627Z   . t.integration.tasks.chain_add
2024-09-04T12:47:28.6904128Z   . t.integration.tasks.chord_add
2024-09-04T12:47:28.6904611Z   . t.integration.tasks.collect_ids
2024-09-04T12:47:28.6905065Z   . t.integration.tasks.delayed_sum
2024-09-04T12:47:28.6905564Z   . t.integration.tasks.delayed_sum_with_soft_guard
2024-09-04T12:47:28.6906062Z   . t.integration.tasks.errback_new_style
2024-09-04T12:47:28.6906540Z   . t.integration.tasks.errback_old_style
2024-09-04T12:47:28.6907040Z   . t.integration.tasks.fail
2024-09-04T12:47:28.6907445Z   . t.integration.tasks.fail_replaced
2024-09-04T12:47:28.6907870Z   . t.integration.tasks.fail_unpickleable
2024-09-04T12:47:28.6908379Z   . t.integration.tasks.identity
2024-09-04T12:47:28.6908797Z   . t.integration.tasks.ids
2024-09-04T12:47:28.6909242Z   . t.integration.tasks.mul
2024-09-04T12:47:28.6909713Z   . t.integration.tasks.print_unicode
2024-09-04T12:47:28.6910137Z   . t.integration.tasks.raise_error
2024-09-04T12:47:28.6910629Z   . t.integration.tasks.rebuild_signature
2024-09-04T12:47:28.6911072Z   . t.integration.tasks.redis_count
2024-09-04T12:47:28.6911763Z   . t.integration.tasks.redis_echo
2024-09-04T12:47:28.6912462Z   . t.integration.tasks.redis_echo_group_id
2024-09-04T12:47:28.6912930Z   . t.integration.tasks.replace_with_chain
2024-09-04T12:47:28.6913446Z   . t.integration.tasks.replace_with_chain_which_raises
2024-09-04T12:47:28.6914051Z   . t.integration.tasks.replace_with_empty_chain
2024-09-04T12:47:28.6914581Z   . t.integration.tasks.replace_with_stamped_task
2024-09-04T12:47:28.6915073Z   . t.integration.tasks.replaced_with_me
2024-09-04T12:47:28.6915614Z   . t.integration.tasks.retry
2024-09-04T12:47:28.6916031Z   . t.integration.tasks.retry_once
2024-09-04T12:47:28.6916466Z   . t.integration.tasks.retry_once_headers
2024-09-04T12:47:28.6917015Z   . t.integration.tasks.retry_once_priority
2024-09-04T12:47:28.6917491Z   . t.integration.tasks.retry_unpickleable
2024-09-04T12:47:28.6917929Z   . t.integration.tasks.return_exception
2024-09-04T12:47:28.6918538Z   . t.integration.tasks.return_nested_signature_chain_chain
2024-09-04T12:47:28.6919123Z   . t.integration.tasks.return_nested_signature_chain_chord
2024-09-04T12:47:28.6919793Z   . t.integration.tasks.return_nested_signature_chain_group
2024-09-04T12:47:28.6920373Z   . t.integration.tasks.return_nested_signature_chord_chain
2024-09-04T12:47:28.6921091Z   . t.integration.tasks.return_nested_signature_chord_chord
2024-09-04T12:47:28.6922192Z   . t.integration.tasks.return_nested_signature_chord_group
2024-09-04T12:47:28.6922994Z   . t.integration.tasks.return_nested_signature_group_chain
2024-09-04T12:47:28.6923878Z   . t.integration.tasks.return_nested_signature_group_chord
2024-09-04T12:47:28.6924582Z   . t.integration.tasks.return_nested_signature_group_group
2024-09-04T12:47:28.6925108Z   . t.integration.tasks.return_priority
2024-09-04T12:47:28.6925537Z   . t.integration.tasks.return_properties
2024-09-04T12:47:28.6926104Z   . t.integration.tasks.second_order_replace1
2024-09-04T12:47:28.6926593Z   . t.integration.tasks.second_order_replace2
2024-09-04T12:47:28.6927079Z   . t.integration.tasks.sleeping
2024-09-04T12:47:28.6927643Z   . t.integration.tasks.soft_time_limit_must_exceed_time_limit
2024-09-04T12:47:28.6928133Z   . t.integration.tasks.tsum
2024-09-04T12:47:28.6928594Z   . t.integration.tasks.write_to_file_and_return_int
2024-09-04T12:47:28.6929219Z   . t.integration.tasks.xsum
2024-09-04T12:47:28.6929633Z   . t.smoke.tasks.long_running_task
2024-09-04T12:47:28.6930100Z   . t.smoke.tasks.noop
2024-09-04T12:47:28.6930443Z   . t.smoke.tasks.replace_with_task
2024-09-04T12:47:28.6930920Z   . t.smoke.tasks.self_termination_delay_timeout
2024-09-04T12:47:28.6931506Z   . t.smoke.tasks.self_termination_exhaust_memory
2024-09-04T12:47:28.6931996Z   . t.smoke.tasks.self_termination_sigkill
2024-09-04T12:47:28.6932485Z   . t.smoke.tasks.self_termination_system_exit
2024-09-04T12:47:28.6933202Z   . t.smoke.tasks.soft_time_limit_lower_than_time_limit
2024-09-04T12:47:28.6933793Z   . t.smoke.tasks.soft_time_limit_must_exceed_time_limit
2024-09-04T12:47:28.6934151Z 
2024-09-04T12:47:28.6935231Z [2024-09-04 12:46:12,254: WARNING/MainProcess] /celery/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
2024-09-04T12:47:28.6936601Z whether broker connection retries are made during startup in Celery 6.0 and above.
2024-09-04T12:47:28.6937407Z If you wish to retain the existing behavior for retrying connections on startup,
2024-09-04T12:47:28.6938093Z you should set broker_connection_retry_on_startup to True.
2024-09-04T12:47:28.6938623Z   warnings.warn(
2024-09-04T12:47:28.6938859Z 
2024-09-04T12:47:28.6939275Z [2024-09-04 12:46:12,270: INFO/MainProcess] Found credentials in environment variables.
2024-09-04T12:47:28.6940133Z [2024-09-04 12:46:14,407: INFO/MainProcess] Connected to sqs://b09f0037a174:4566//
2024-09-04T12:47:28.6941612Z [2024-09-04 12:46:14,407: WARNING/MainProcess] /celery/celery/worker/consumer/consumer.py:508: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer  [...]

2024-09-08 11:03 UTC, Nusnus approved these changes

2024-09-08 11:03 UTC, merged