Add log when global qos is disabled
celery/celery pull request #9296
Opened 2024-09-18 13:34 UTC by thedrow

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

We should report to the user that global QoS is disabled.
This PR adds a log when that happens.

2024-09-18 14:06 UTC, Nusnus requested changes
Except the missing tests all good

2024-09-18 14:06 UTC, Nusnus commented on celery/worker/consumer/tasks.py
> +            logger.info("Global QoS is disabled. Prefetch count in now static.")
Please add unit tests 🙏 @thedrow

2024-09-24 09:48 UTC, thedrow commented on celery/worker/consumer/tasks.py
> +            logger.info("Global QoS is disabled. Prefetch count in now static.")
Added a unit test.

2024-09-24 10:11 UTC, auvipy approved these changes

2024-09-24 10:45 UTC, Nusnus approved these changes

2024-09-24 10:45 UTC, merged