Add native incr support for GCSBackend
celery/celery pull request #9302
Opened 2024-09-19 07:58 UTC by haimjether

* Implement chord ref count on top of Google Firestore
 * Improve runtime and reduce amount of data read from GCS.
 * Add tests
 * Update docs

2024-09-19 08:41 UTC, auvipy requested changes
thanks for the patch! this will be really great addition. will you please also look at pypy failure and increase test coverage?

2024-09-19 08:50 UTC, haimjether commented
> thanks for the patch! this will be really great addition. will you please also look at pypy failure and increase test coverage?

np, on it :)

2024-09-24 10:20 UTC, haimjether commented
I struggle to fix the grpcio installation (required by `google-cloud-firestore`)  for pypy in the test image. 
A bit of comfort is that  it looks like a familiar issue:  https://github.com/grpc/grpc/issues/29517

FWIW, was able to build the `grpcio-1.66.1-pp310-pypy310_pp73-linux_x86_64.whl`  from sources in clean environment which I created (without tox being involved) on Ubuntu 24.04.  The whole thing takes ~8.5 minutes which IMHO isn't that nice to trigger for every test.

Any chance we can push it to some extra wheel house e.g https://celery.github.io/celery-wheelhouse/repo/simple/ , since grpcio doesn't have binary releases for pypy ?

2024-09-25 13:18 UTC, thedrow commented
@haimjether Please contribute the wheel in https://github.com/celery/celery-wheelhouse

2024-09-27 16:34 UTC, Nusnus reviewed
Any update on the PR? 🙏

2024-10-03 06:20 UTC, haimjether commented
Added https://github.com/celery/celery-wheelhouse/pull/4 for the grpcio wheel - once it's merged the pypy tests should pass

2024-10-03 08:10 UTC, thedrow commented
@haimjether The wheel is merged. Please rebase.

2024-10-03 09:38 UTC, thedrow requested changes
[Unit tests](https://github.com/celery/celery/actions/runs/11159409087/job/31017739244?pr=9302#step:7:993) are failing for 3.13.

2024-10-03 10:03 UTC, haimjether commented
> [Unit tests](https://github.com/celery/celery/actions/runs/11159409087/job/31017739244?pr=9302#step:7:993) are failing for 3.13.
The issue is in lack of support of Google's Firestore for Python 3.13. 

Created an issue https://github.com/googleapis/python-firestore/issues/973

2024-10-05 14:59 UTC, Nusnus reviewed
If you want, you may disable 3.13 (remove from list in workflow) to see if the rest of the CI passes.
We can revert the commit before merge.

2024-10-06 06:02 UTC, haimjether commented
@Nusnus ,  IMHO looks like everything but the rc python3.13 passes

2024-10-13 17:48 UTC, Nusnus commented
> @Nusnus , IMHO looks like everything but the rc python3.13 passes

Isn’t it a real bug/error?
```
2024-10-13T17:45:32.6369811Z ==================================== ERRORS ====================================
2024-10-13T17:45:32.6370908Z _________________ ERROR collecting t/unit/backends/test_gcs.py _________________
2024-10-13T17:45:32.6371932Z t/unit/backends/test_gcs.py:7: in <module>
2024-10-13T17:45:32.6372576Z     from celery.backends.gcs import GCSBackend
2024-10-13T17:45:32.6374064Z celery/backends/gcs.py:30: in <module>
2024-10-13T17:45:32.6374991Z     from google.cloud import firestore, firestore_admin_v1
2024-10-13T17:45:32.6376422Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/__init__.py:18: in <module>
2024-10-13T17:45:32.6377802Z     from .services.firestore_admin import FirestoreAdminClient
2024-10-13T17:45:32.6379129Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/__init__.py:16: in <module>
2024-10-13T17:45:32.6380386Z     from .client import FirestoreAdminClient
2024-10-13T17:45:32.6381639Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/client.py:53: in <module>
2024-10-13T17:45:32.6383052Z     from google.cloud.firestore_admin_v1.services.firestore_admin import pagers
2024-10-13T17:45:32.6384543Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/pagers.py:40: in <module>
2024-10-13T17:45:32.6385801Z     from google.cloud.firestore_admin_v1.types import field
2024-10-13T17:45:32.6386890Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/__init__.py:19: in <module>
2024-10-13T17:45:32.6387911Z     from .database import (
2024-10-13T17:45:32.6388864Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/database.py:34: in <module>
2024-10-13T17:45:32.6389745Z     class Database(proto.Message):
2024-10-13T17:45:32.6390729Z .tox/3.13-unit/lib/python3.13/site-packages/proto/message.py:279: in __new__
2024-10-13T17:45:32.6391696Z     file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
2024-10-13T17:45:32.6393277Z .tox/3.13-unit/lib/python3.13/site-packages/proto/_file_info.py:104: in generate_file_pb
2024-10-13T17:45:32.6394085Z     pool.Add(self.descriptor)
2024-10-13T17:45:32.6395176Z E   TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.firestore.admin.v1.Database.__firstlineno__’
```

2024-10-13 19:09 UTC, haimjether commented
> @haimjether
> 
> > @Nusnus , IMHO looks like everything but the rc python3.13 passes
> 
> Isn’t it a real bug/error?
> 
> ```
> 2024-10-13T17:45:32.6369811Z ==================================== ERRORS ====================================
> 2024-10-13T17:45:32.6370908Z _________________ ERROR collecting t/unit/backends/test_gcs.py _________________
> 2024-10-13T17:45:32.6371932Z t/unit/backends/test_gcs.py:7: in <module>
> 2024-10-13T17:45:32.6372576Z     from celery.backends.gcs import GCSBackend
> 2024-10-13T17:45:32.6374064Z celery/backends/gcs.py:30: in <module>
> 2024-10-13T17:45:32.6374991Z     from google.cloud import firestore, firestore_admin_v1
> 2024-10-13T17:45:32.6376422Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/__init__.py:18: in <module>
> 2024-10-13T17:45:32.6377802Z     from .services.firestore_admin import FirestoreAdminClient
> 2024-10-13T17:45:32.6379129Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/__init__.py:16: in <module>
> 2024-10-13T17:45:32.6380386Z     from .client import FirestoreAdminClient
> 2024-10-13T17:45:32.6381639Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/client.py:53: in <module>
> 2024-10-13T17:45:32.6383052Z     from google.cloud.firestore_admin_v1.services.firestore_admin import pagers
> 2024-10-13T17:45:32.6384543Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/services/firestore_admin/pagers.py:40: in <module>
> 2024-10-13T17:45:32.6385801Z     from google.cloud.firestore_admin_v1.types import field
> 2024-10-13T17:45:32.6386890Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/__init__.py:19: in <module>
> 2024-10-13T17:45:32.6387911Z     from .database import (
> 2024-10-13T17:45:32.6388864Z .tox/3.13-unit/lib/python3.13/site-packages/google/cloud/firestore_admin_v1/types/database.py:34: in <module>
> 2024-10-13T17:45:32.6389745Z     class Database(proto.Message):
> 2024-10-13T17:45:32.6390729Z .tox/3.13-unit/lib/python3.13/site-packages/proto/message.py:279: in __new__
> 2024-10-13T17:45:32.6391696Z     file_info.generate_file_pb(new_class=cls, fallback_salt=full_name)
> 2024-10-13T17:45:32.6393277Z .tox/3.13-unit/lib/python3.13/site-packages/proto/_file_info.py:104: in generate_file_pb
> 2024-10-13T17:45:32.6394085Z     pool.Add(self.descriptor)
> 2024-10-13T17:45:32.6395176Z E   TypeError: Couldn't build proto file into descriptor pool: duplicate symbol 'google.firestore.admin.v1.Database.__firstlineno__’
> ```

It is .
Google's firestore package is broken in Python 3.13 
I re-pinged google folks once again today  :shrug:

2024-10-14 12:22 UTC, auvipy reviewed
may be we could ignore/skip python 3.13 test for this PR as not all the dependencies of celery project still not working with python 3.13 yet?

2024-10-14 12:54 UTC, Nusnus commented
> may be we could ignore/skip python 3.13 test for this PR as not all the dependencies of celery project still not working with python 3.13 yet?

I agree with @auvipy , let's do it

2024-10-14 16:36 UTC, haimjether commented
Do I need to make this change as  part of the patch ?

2024-10-14 16:45 UTC, Nusnus commented
@haimjether 
> Do I need to make this change as part of the patch ?

Hmm, you’re thinking about using a different PR so we can easily revert it later?
I like your idea haha

Sure go for it and ping me for a fast review.

2024-10-14 17:30 UTC, Nusnus commented
@haimjether 
> Actually I meant should my PR change to to somehow ignore Python 3.13 😊

Yeah sure np just commit a “skip if py13” and link the relevant issue in the reason string.
Push to this PR & rebase/merge `main`.

Ping me if you need any help.

2024-10-14 20:40 UTC, Nusnus reviewed
The CI passes, thanks. I'll review tomorrow!

2024-10-17 14:58 UTC, Nusnus approved these changes
Thank you, looks great!

P.S
Do you think you can also cover the few remaining code coverage warnings?
Not critical though.

2024-10-17 15:25 UTC, Nusnus commented
> LGTM

@auvipy please review the changes and approve/merge if it LGTyou2 haha

2024-10-17 18:38 UTC, auvipy approved these changes

2024-10-17 18:39 UTC, merged

2025-04-24 15:07 UTC, benglewis reviewed
I'm having some trouble with this PR's changes. I'd appreciate if it is possible to change it a little

2025-04-24 16:26 UTC, haimjether commented on docs/userguide/configuration.rst
> +    This gcs backend driver requires :pypi:`google-cloud-storage` and :pypi:`google-cloud-firestore`.
@benglewis , it is required for the native chord support: https://github.com/celery/celery/pull/9302

2025-04-24 16:31 UTC, benglewis commented on docs/userguide/configuration.rst
> +    This gcs backend driver requires :pypi:`google-cloud-storage` and :pypi:`google-cloud-firestore`.
I don't mean to be too stupid, but what exactly does that mean? 🙈 What are chords in the context of Celery? Why is this new? Were chords non-native before? Is it really necessary for them to be required now?

2025-04-24 16:45 UTC, haimjether commented on docs/userguide/configuration.rst
> +    This gcs backend driver requires :pypi:`google-cloud-storage` and :pypi:`google-cloud-firestore`.
Chords have been an integral part of Celery since v2.3 :)


Please have a look here: 
https://docs.celeryq.dev/en/latest/userguide/canvas.html#id11

Native means that the backend implements the reference count in a very efficient way.

2025-04-24 16:48 UTC, haimjether commented on t/unit/backends/test_gcs.py
> +    reason="https://github.com/googleapis/python-firestore/issues/973",
You can upgrade to Python 3.13, without the GCS. Does that help ?

Or did you mean that you are  planning to use Celery with GCS and Pub/Sub with Python 3.13 ?

2025-04-27 09:04 UTC, auvipy commented on t/unit/backends/test_gcs.py
> +    reason="https://github.com/googleapis/python-firestore/issues/973",
I have opened a PR https://github.com/celery/celery/pull/9677 to fix this issue of testing python 3.13