Pydantic typehints
celery/celery pull request #9319
Opened 2024-09-27 22:35 UTC by mathiasertl

## Description

Various updates to Pydantic model handling:

* `Optional[]` is now supported.
* Fix generic typehints such as `list[str]` or `dict[str, str]` (fixes #9316)
* Update documentation.
* Add more tests for various argument types.

Fixes #9316. Also relates to #9023 and #8751 of course.

Tagging @Nusnus , as requested.

2024-09-27 22:42 UTC, mathiasertl commented
Hi @Nusnus ,

Python 3.9 is failing in what I think may not be related to my changes:

```
 debug - 2024-09-27 22:39:23,605 -- Report creating result --- {"result": "RequestResult(error=RequestError(code='HTTP Error 400', params={}, description='{\"message\":\"Token required because branch is protected\"}\\n'), warnings=[], status_code=400, text='{\"message\":\"Token required because branch is protected\"}\\n')"}
error - 2024-09-27 22:39:23,605 -- Report creating failed: {"message":"Token required because branch is protected"}
Error: Codecov:
                        Failed to properly create report: The process '/home/runner/_work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```

I tried running tox for 3.9 and that works :shrug: .

I assume the two codecov/ failures are due to the same reasons.

2024-09-28 01:21 UTC, Nusnus requested changes
Code cov sometimes fails the unit tests which stops the CI.. It’s a known issue and not related to the PR of course. I’ve rerun the CI.

Even though the unit tests have passed, codecov still says there is untested code. Is it wrong? because I see you added more tests, but I didn’t compare each one to the matching codecov warning.

2024-09-28 08:48 UTC, mathiasertl commented
> codecov still says there is untested code. Is it wrong?

To be honest, I have never seen `codecov` produce any meaningful output. In `annotations.py`, the function declarations are not covered, but the rest of the code is. In `apps.py`, some top-level imports (that are not even new) are not covered anymore.

2024-09-28 09:13 UTC, mathiasertl commented
Made a minor change and everything fails because of codecov again. I cannot restart it myself, it seems.

2024-09-28 10:04 UTC, Nusnus approved these changes
LGTM

2024-09-28 10:05 UTC, merged