fix(perform_pending_operations): prevent task duplication on shutdown…
celery/celery pull request #9348
Opened 2024-10-11 10:15 UTC by moaddib666

## Description

Resolved an issue where completed tasks were restored on shutdown, causing duplicates for recursive tasks in gevent/eventlet modes (#5663). The problem was that `perform_pending_operations()` was not called before `SystemExit` was raised in `synloop`.

Fixes #5663

2024-10-11 10:51 UTC, auvipy requested changes
Thanks for the patch! But we will need tests to ensure the solution dont create any regression

2024-10-11 11:03 UTC, Nusnus requested changes
@moaddib666 
> Thanks for the patch! But we will need tests to ensure the solution dont create any regression 

See also shutdown tests in the smoke tests:
https://github.com/celery/celery/blob/main/t%2Fsmoke%2Ftests%2Ftest_worker.py

2024-10-11 11:05 UTC, moaddib666 commented
Added unit tests on loop

2024-10-11 11:18 UTC, moaddib666 commented
Hi @Nusnus and @auvipy great to hear your feedback, hope you are doing well !

I've reviewed the worker tests and believe we may not need to modify them, as our changes are minimal—we're just ensuring that the iteration cycle executes before a `SystemExit` is raised. This way, all existing workflows should continue to function as expected.

I've added a unit test for synloop to cover the expected scenario. I also manually verified that the test fails if I revert the changes, confirming that the test correctly detects the issue.

2024-10-12 11:04 UTC, Nusnus reviewed
There's an issue with pypy. Probably not related to this PR, but it blocks the CI for now.
I'll update this branch once it's fixed so we can review it properly.

2024-10-13 18:12 UTC, Nusnus commented
> There's an issue with pypy. Probably not related to this PR, but it blocks the CI for now. I'll update this branch once it's fixed so we can review it properly.

Handled.

2024-10-13 18:16 UTC, Nusnus requested changes
Can you please retry this [quick test](https://github.com/celery/celery/issues/5663#issuecomment-517281627) with your fix and share the results?

2024-10-13 18:26 UTC, moaddib666 commented
> @moaddib666 
> Can you please retry this [quick test](https://github.com/celery/celery/issues/5663#issuecomment-517281627) with your fix and share the results?

hi, sure, will check

2024-10-14 18:27 UTC, Nusnus commented
> > @moaddib666 
> > Can you please retry this [quick test](https://github.com/celery/celery/issues/5663#issuecomment-517281627) with your fix and share the results?
> 
> hi, sure, will check 

Thanks!
LMK so we can finish the review @moaddib666

2024-10-15 10:28 UTC, moaddib666 commented
Hi, @Nusnus 

It looks like the count of unacknowledged tasks decreases, but with low concurrency (1-5 workers), we encounter the following scenario when a worker is stopped during task processing:

synloop -> Exits with SystemExit.
TaskSuccess -> Consumer.call_soon is invoked.
Consumer._pending_operations increases (but nobody is processing it).
Consumer.shutdown is invoked.
Blueprint.shutdown is invoked.
Task Restored.

Upon re-checking, it appears that we could call Consumer.perform_pending_operations just before Blueprint.shutdown. This would ensure all pending operations (promises) are processed before the blueprint proceeds with its shutdown operations.

I’m running some additional tests now to confirm this solution and ensure it doesn't negatively impact the entire system.

2024-10-15 10:30 UTC, Nusnus commented
> Hi, @Nusnus 
> 
> It looks like the count of unacknowledged tasks decreases, but with low concurrency (1-5 workers), we encounter the following scenario when a worker is stopped during task processing:
> 
> synloop -> Exits with SystemExit.
> TaskSuccess -> Consumer.call_soon is invoked.
> Consumer._pending_operations increases (but nobody is processing it).
> Consumer.shutdown is invoked.
> Blueprint.shutdown is invoked.
> Task Restored.
> 
> Upon re-checking, it appears that we could call Consumer.perform_pending_operations just before Blueprint.shutdown. This would ensure all pending operations (promises) are processed before the blueprint proceeds with its shutdown operations.
> 
> I’m running some additional tests now to confirm this solution and ensure it doesn't negatively impact the entire system.

Great work! Thank you.
Ping me for the next update!

2024-10-15 11:22 UTC, Nusnus requested changes
Checkout `tox -e lint` to see the errors locally

2024-10-15 11:47 UTC, moaddib666 commented
@Nusnus Sorry about lint, just been in a hurry. 
Looks like that's it, all messages been acknowledged, all tests passed on my lab https://github.com/moaddib666/celery-gevent-lab you can use to check the results just install celery from sources pip -e {pathToCelery}[sqs]

2024-10-15 13:02 UTC, Nusnus commented
> @Nusnus Sorry about lint, just been in a hurry. 
> Looks like that's it, all messages been acknowledged, all tests passed on my lab https://github.com/moaddib666/celery-gevent-lab you can use to check the results just install celery from sources pip -e {pathToCelery}[sqs]

Awesome!
I'll check it soon thanks!

2024-10-17 13:21 UTC, Nusnus approved these changes
Thank you very much!

2024-10-17 13:23 UTC, Nusnus commented
@auvipy everything looks right here.
Can we proceed to merge?

2024-10-17 18:42 UTC, auvipy approved these changes

2024-10-17 18:43 UTC, merged