Pass timeout and confirm_timeout to producer.publish()
celery/celery pull request #9374
Opened 2024-10-23 08:39 UTC by thedrow

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

Before this PR, publishing ignored the timeout and confirm_timeout since it was not passed down the chain of calls.
We now explicitly pass them to the `producer.publish()` call.

Related PRs: https://github.com/celery/kombu/pull/2166 and https://github.com/celery/kombu/pull/2167.

2024-10-23 09:54 UTC, thedrow commented
The coverage failure seems like a false positive.

2024-10-23 11:30 UTC, auvipy approved these changes

2024-10-26 21:43 UTC, Nusnus requested changes
Don't we need to release this change before we can merge this PR @thedrow ?
https://github.com/celery/kombu/pull/2167

2024-10-28 11:07 UTC, Nusnus approved these changes

2024-10-28 11:07 UTC, merged