fix(django): catch the right error when trying to close db connection
celery/celery pull request #9392
Opened 2024-10-31 10:07 UTC by Lotram

## Description

Fixes #9310 
As explained in the issue, `_maybe_close_db_fd` tries to catch django's db-agnostic errors (such as `django.db.InterfaceError`), but `_maybe_close_fd` raises a db-specific error (eg. `pyscog2.InterfaceError`). 

To fix that, we wrap the call to `_maybe_close_fd` with the `c.wrap_database_errors` context manager (cf [here](https://github.com/django/django/blob/main/django/db/backends/base/base.py#L663)), made for this exact purpose. It prevents the worker to keep raising errors when initializing a process

2024-10-31 14:59 UTC, Lotram commented
I don't really understand why Codecov is complaining, as the line I added [is tested](https://app.codecov.io/gh/celery/celery/commit/84a742df3027b3038277e1071936b6b48fadf89d/blob/celery/fixups/django.py#L176). And why are all the import lines considered as not tested ?

2024-11-02 08:21 UTC, auvipy requested changes
can you please increase test coverage for the proposed change please?

2024-11-02 22:42 UTC, Lotram commented
I'll try to improve the coverage, but I don't get why codecov is complaining, thz line I added is tested, and the only line it's highligting is the function definition

2024-11-03 14:10 UTC, Lotram commented
@auvipy I honestly don't know how to improve the coverage, by looking at [the report](https://app.codecov.io/gh/celery/celery/pull/9392/blob/celery/fixups/django.py), only the function signatures are not covered. Isn't there a problem with the codecov configuration ?

2024-11-03 14:24 UTC, Lotram commented
@auvipy it's seems related to [this pytest-cov issue](https://github.com/pytest-dev/pytest-cov/issues/184).

2024-12-14 08:57 UTC, auvipy requested changes
we need to check the smoke test failures. it should be good addition to v5.5

2024-12-17 18:56 UTC, Nusnus commented
> we need to check the smoke test failures. 

Fixed!

2024-12-17 18:59 UTC, Nusnus approved these changes
LGTM, thanks!

2024-12-17 19:01 UTC, Nusnus commented
@auvipy I’d like to merge this before the next RC, do you mind giving it a quick look please?
We need your approval to continue my friend.

2024-12-25 17:51 UTC, auvipy commented
Sure

2024-12-25 18:08 UTC, auvipy approved these changes

2024-12-25 18:09 UTC, merged