Fix cassandra backend port settings not working
celery/celery pull request #9465
Opened 2024-12-13 13:29 UTC by kairi003

*Note*: Before submitting this pull request, please review our [contributing
guidelines](https://docs.celeryq.dev/en/main/contributing.html).

## Description

Fixes #5226 : this issue was closed but not yet fixed now.

2024-12-14 08:45 UTC, auvipy requested changes
can you please update the relevant tests as well?  many test builds are failing

2024-12-14 14:06 UTC, Nusnus commented
> can you please update the relevant tests as well?  many test builds are failing

Smoke on Python 3.8 is having problems in main as well.
It's pretty new.

I'll fix it today/tomorrow and then we can rebase this PR to see if indeed we get 100% green

2024-12-14 15:30 UTC, kairi003 commented
This is just a personal suggestion, but since Python 3.8 has reached its EOL, it might be better to exclude it from the test.

2024-12-21 05:34 UTC, kairi003 commented
@auvipy hi, this pr rebased with @Nusnus 's work and pass all test!

2024-12-22 09:19 UTC, auvipy requested changes
I would still suggest to add / update unit tests for the change

2024-12-23 12:41 UTC, kairi003 commented
@Nusnus @auvipy 
Only one test is failing and I don't know why...
I believe it probably has nothing to do with this PR change.
Does this happen in main now, or is it a random problem and a re-run will fix it?

2024-12-23 12:50 UTC, Nusnus commented
> @Nusnus @auvipy 
> Only one test is failing and I don't know why...
> I believe it probably has nothing to do with this PR change.
> Does this happen in main now, or is it a random problem and a re-run will fix it?

Flaky. Restarting.

2024-12-23 13:30 UTC, auvipy approved these changes

2024-12-23 13:30 UTC, merged

2024-12-23 13:31 UTC, auvipy commented
Thanks both of you